// ============================================================================
// Flashcards — content (hand-authored)
// ----------------------------------------------------------------------------
// This file IS the flashcard deck. It mirrors the Study Notes groups so the two
// stay in sync. To add material: append cards to the matching group below (or add
// a new group). There is no editor and nothing is persisted here — edit directly.
//
// GROWTH WORKFLOW: whenever you add a notes section in notes-data.js, add matching
// flashcards here in a group with the SAME id/title. Pure content additions do NOT
// need a version bump or changelog entry (same convention as the notes).
//
// A group:
//   { id: "kebab-id", title: "Group Title", cards: [ ...cards ] }
//
// A card (multiple choice):
//   {
//     id: "unique-kebab-id",        // unique across the whole deck
//     q: "The question / prompt (front of the card)",
//     a: "The correct answer (back of the card)",
//     distractors: ["wrong 1", "wrong 2", "wrong 3"],  // exactly 3, all wrong
//     note: "optional extra context shown after answering / on the back",
//   }
//
// Rules the tests enforce:
//   • group ids are unique; card ids are unique across the deck
//   • every card has a non-empty q and a
//   • distractors is an array of exactly 3 non-empty strings
//   • no distractor equals the answer (case-sensitive); distractors are distinct
// ============================================================================

export const FLASHCARDS = [
  {
    id: "nt-intro",
    module: "m2",
    title: "Introduction to Number Theory",
    cards: [
      { id: "nt-intro-what", q: "Number theory is the study of…", a: "the integers and their structure (divisibility, primes, congruences)",
        distractors: ["the real numbers and limits", "sets and functions in general", "logical connectives"],
        note: "Foundational to cryptography, hashing, and algorithms." },
      { id: "nt-intro-closure", q: "The integers ℤ are closed under which operations?", a: "addition, subtraction, and multiplication",
        distractors: ["all four including division", "only addition", "multiplication and division"],
        note: "3 / 2 isn't an integer — divisibility studies when division comes out even." },
      { id: "nt-intro-divdef", q: "By definition, a | b means…", a: "b = a·k for some integer k",
        distractors: ["a = b·k for some integer k", "a / b is an integer with remainder", "a and b share no factors"],
        note: "a is a factor of b; b is a multiple of a." },
      { id: "nt-intro-vocab", q: "If a | b, then b is called…", a: "a multiple of a",
        distractors: ["a divisor of a", "a factor of a", "coprime to a"],
        note: "And a is a divisor/factor of b." },
      { id: "nt-intro-special", q: "Which statement is true for all integers n?", a: "1 | n and n | 0",
        distractors: ["n | 1 for every n", "0 | n for every n", "n | n only when n is prime"],
        note: "1 divides everything; every integer divides 0." },
    ],
  },
  {
    id: "tk-parity-divisibility",
    module: "m2",
    title: "Parity & Divisibility",
    cards: [
      { id: "tk-pd-even-def", q: "Formally, an integer n is even when…", a: "n = 2k for some integer k",
        distractors: ["n = 2k + 1 for some integer k", "n is divisible by every integer", "n / 2 is irrational"],
        note: "Odd means n = 2k + 1." },
      { id: "tk-pd-divides", q: "What does a | b mean?", a: "b = a·k for some integer k",
        distractors: ["a = b·k for some integer k", "a / b is an integer's remainder", "a and b are coprime"],
        note: "a is a factor of b; b is a multiple of a." },
      { id: "tk-pd-nsq", q: "n² is even exactly when…", a: "n is even",
        distractors: ["n is odd", "n is prime", "always — every square is even"],
        note: "even × even = even; odd × odd = odd." },
      { id: "tk-pd-oddprod", q: "The product of two odd integers is…", a: "odd",
        distractors: ["even", "sometimes even, sometimes odd", "prime"],
        note: "(2a+1)(2b+1) = 2(2ab+a+b)+1." },
      { id: "tk-pd-transitive", q: "If a | b and b | c, then…", a: "a | c",
        distractors: ["c | a", "a | (b + c) only", "nothing follows"],
        note: "Divisibility is transitive." },
      { id: "tk-pd-lincombo", q: "If a | b and a | c, then a divides…", a: "bx + cy for all integers x, y",
        distractors: ["only b + c", "only bc", "b / c"],
        note: "a divides every integer linear combination of b and c." },
      { id: "tk-pd-bound", q: "If a | b and b ≠ 0, what size relation holds?", a: "|a| ≤ |b|",
        distractors: ["|a| ≥ |b|", "|a| = |b|", "no relation is guaranteed"],
        note: "A nonzero multiple is at least as large as its divisor." },
    ],
  },
  {
    id: "nt-divisibility-template",
    module: "m2",
    title: "The Divisibility-Proof Template",
    cards: [
      { id: "nt-dt-step1", q: "The first step of a divisibility proof is to…", a: "introduce variables with their domains and state your assumptions",
        distractors: ["immediately write the conclusion", "divide both sides by a", "guess a counterexample"],
        note: "\"Let a, b, c be integers…\" plus the antecedent." },
      { id: "nt-dt-unpack", q: "To \"unpack\" the hypothesis a | b, you write…", a: "b = a·m for some integer m",
        distractors: ["b / a is an integer", "a = b·m for some integer m", "gcd(a, b) = 1"],
        note: "Apply the definition of divides to get an equation with a fresh integer." },
      { id: "nt-dt-nofrac", q: "In a divisibility proof you should never need…", a: "a fraction or a division sign",
        distractors: ["a multiplication", "a new integer variable", "the definition of divides"],
        note: "Divisibility works entirely through multiplication." },
      { id: "nt-dt-closure", q: "After forming a witness like m·n, what must you justify?", a: "that m·n is an integer (closure)",
        distractors: ["that m·n is prime", "that m·n is positive", "that m ≠ n"],
        note: "The definition of divides requires an integer witness." },
      { id: "nt-dt-repackage", q: "You've shown c = a·(m·n) with m·n ∈ ℤ. You conclude…", a: "a | c",
        distractors: ["c | a", "a | (m·n)", "gcd(a, c) = m·n"],
        note: "Repackage the equation using the definition of divides." },
      { id: "nt-dt-newvars", q: "Every new variable you introduce in the proof must…", a: "be properly defined — where it comes from and its domain",
        distractors: ["be a prime number", "appear in the conclusion", "be positive"],
        note: "Undefined variables make the proof invalid." },
    ],
  },
  {
    id: "tk-division-modular",
    module: "m2",
    title: "Division & Modular Arithmetic",
    cards: [
      { id: "tk-dm-qrt", q: "The Division Theorem writes a = dq + r (d > 0) with…", a: "0 ≤ r < d, and q, r unique",
        distractors: ["0 < r ≤ d", "−d < r < d", "r any integer"],
        note: "q = ⌊a/d⌋, r = a mod d." },
      { id: "tk-dm-cong", q: "a ≡ b (mod m) is defined as…", a: "m | (a − b)",
        distractors: ["a | (b − m)", "a − b = m", "gcd(a, b) = m"],
        note: "Same remainder mod m." },
      { id: "tk-dm-mult", q: "If a ≡ b and c ≡ d (mod m), then…", a: "ac ≡ bd (mod m)",
        distractors: ["ac ≡ bd only if m is prime", "a/c ≡ b/d (mod m)", "nothing about products"],
        note: "Congruences add and multiply." },
      { id: "tk-dm-inverse", q: "a has a multiplicative inverse mod m exactly when…", a: "gcd(a, m) = 1",
        distractors: ["a is prime", "a < m", "m is even"],
        note: "Coprime to the modulus." },
      { id: "tk-dm-fermat", q: "Fermat's Little Theorem: if p is prime and p ∤ a, then…", a: "aᵖ⁻¹ ≡ 1 (mod p)",
        distractors: ["aᵖ ≡ 0 (mod p)", "aᵖ⁻¹ ≡ a (mod p)", "a² ≡ 1 (mod p)"],
        note: "Also aᵖ ≡ a (mod p) for all a." },
    ],
  },
  {
    id: "tk-congruence-classes",
    module: "m2",
    title: "Modular Arithmetic & Congruence Classes",
    cards: [
      { id: "tk-cc-bicond", q: "The Biconditional Theorem states a ≡ b (mod n) is equivalent to…", a: "n | (a − b)",
        distractors: ["a | (b − n)", "gcd(a, b) = n", "a − b = n"],
        note: "The main tool of modular arithmetic — turns congruence into divisibility." },
      { id: "tk-cc-strategy", q: "The easiest way to prove a ≡ b (mod n) is usually to…", a: "show n | (a − b) using the divisibility toolkit",
        distractors: ["compute both remainders by long division", "factor n into primes", "apply Fermat's Little Theorem"],
        note: "The biconditional lets you reuse divisibility proofs." },
      { id: "tk-cc-forward", q: "The forward direction (⇒) of the biconditional gives you…", a: "n | (a − b), a divisibility fact to work with",
        distractors: ["a ≡ b (mod n) from n | (a − b)", "the value of gcd(a, n)", "a multiplicative inverse"],
        note: "Reverse (⇐): from n | (a − b) conclude a ≡ b (mod n)." },
      { id: "tk-cc-pattern", q: "Proving ⇒ and ⇐ separately is the same pattern used for…", a: "set equality (A ⊆ B and B ⊆ A) and bijectivity",
        distractors: ["proof by induction", "the Euclidean algorithm", "the pigeonhole principle"],
        note: "Biconditional proofs recur throughout the course." },
      { id: "tk-cc-example", q: "Is 47 ≡ 11 (mod 9)?", a: "Yes — 47 − 11 = 36 = 9·4, so 9 | 36",
        distractors: ["No — 9 does not divide 36", "Yes — because 47 and 11 are both odd", "Cannot be determined"],
        note: "Check whether n divides the difference." },
      { id: "tk-cc-zerodiv", q: "In ℤ₁₂, [3]·[4] = [0] even though neither is [0]. [3] and [4] are called…", a: "zero divisors",
        distractors: ["units", "inverses", "primes"],
        note: "Nonzero elements whose product is 0." },
      { id: "tk-cc-cancel", q: "You can cancel [a] in a congruence mod n exactly when…", a: "[a] is invertible, i.e. gcd(a, n) = 1",
        distractors: ["a is prime", "a < n", "a is even"],
        note: "You can't cancel a zero divisor." },
      { id: "tk-cc-dichotomy", q: "In ℤₙ, a nonzero element [a] is…", a: "invertible if gcd(a, n) = 1, otherwise a zero divisor",
        distractors: ["always invertible", "always a zero divisor", "invertible only if a is prime"],
        note: "No middle ground — exactly one of the two." },
    ],
  },
  {
    id: "tk-gcd-euclid",
    module: "m2",
    title: "GCD & the Euclidean Algorithm",
    cards: [
      { id: "tk-ge-def", q: "gcd(a, b) is…", a: "the largest integer that divides both a and b",
        distractors: ["the smallest common multiple of a and b", "a·b divided by 2", "the largest of a and b"],
        note: "By convention gcd(a, 0) = |a|." },
      { id: "tk-pg-coprime", q: "Two integers are coprime (relatively prime) when…", a: "gcd(a, b) = 1",
        distractors: ["both are prime", "one divides the other", "a + b is prime"],
        note: "No common factor besides 1." },
      { id: "tk-pg-euclidalg", q: "The Euclidean algorithm uses which identity?", a: "gcd(a, b) = gcd(b, a mod b)",
        distractors: ["gcd(a, b) = gcd(a − b, b) only", "gcd(a, b) = a·b", "gcd(a, b) = gcd(a, a + b)"],
        note: "Recurse until the second term is 0." },
      { id: "tk-ge-lastrem", q: "In the Euclidean algorithm, the gcd is…", a: "the last nonzero remainder",
        distractors: ["the first remainder", "the final quotient", "the sum of the remainders"],
        note: "gcd(48,18): 48=2·18+12, 18=1·12+6, 12=2·6+0 → gcd = 6." },
      { id: "tk-pg-bezout", q: "Bézout's Identity says gcd(a, b) can be written as…", a: "ax + by for some integers x, y",
        distractors: ["a·b / lcm(a,b) only", "a^x · b^y", "the largest of a and b"],
        note: "gcd is the smallest positive such combination." },
      { id: "tk-ge-ext", q: "The Extended Euclidean Algorithm is used to…", a: "find the Bézout coefficients x, y (and modular inverses)",
        distractors: ["factor a number into primes", "test whether a number is prime", "compute a^n mod m quickly"],
        note: "Back-substitute the Euclidean steps to write gcd = ax + by." },
      { id: "tk-ge-lcm", q: "For positive a, b, gcd(a, b) · lcm(a, b) = ?", a: "a · b",
        distractors: ["a + b", "gcd(a, b)²", "|a − b|"],
        note: "In general gcd(a,b)·lcm(a,b) = |a·b|." },
    ],
  },
  {
    id: "tk-primes-gcd",
    module: "m2",
    title: "Primes & Factorization",
    cards: [
      { id: "tk-pg-euclid", q: "Euclid's Lemma: if p is prime and p | ab, then…", a: "p | a or p | b",
        distractors: ["p | a and p | b", "p | (a + b)", "a | p or b | p"],
        note: "The defining property of primes." },
      { id: "tk-pg-fta", q: "The Fundamental Theorem of Arithmetic guarantees…", a: "every integer > 1 has a unique prime factorization",
        distractors: ["every integer is prime or 1", "there are finitely many primes", "gcd is always 1"],
        note: "Unique up to the order of factors." },
      { id: "tk-pg-infinite", q: "Euclid's proof that primes are infinite considers…", a: "p₁···pₖ + 1, which has a prime factor not in the list",
        distractors: ["the largest prime squared", "p₁···pₖ − 1 only", "2ⁿ − 1 for all n"],
        note: "Contradiction: any finite list is incomplete." },
      { id: "tk-pg-composite", q: "An integer n ≥ 2 is composite when…", a: "n = ab for some integers with 1 < a, b < n",
        distractors: ["its only divisors are 1 and n", "it is odd and not prime", "gcd(n, 1) = n"],
        note: "Composite = not prime (for n ≥ 2)." },
      { id: "tk-pg-one", q: "The number 1 is…", a: "neither prime nor composite",
        distractors: ["prime", "composite", "both prime and composite"],
        note: "A convention that keeps unique factorization clean." },
      { id: "tk-pg-fta-divis", q: "Given prime factorizations, a | b exactly when…", a: "every prime in a appears in b with an exponent at least as large",
        distractors: ["a and b share at least one prime", "a has fewer prime factors than b", "a and b are coprime"],
        note: "12 = 2²·3 divides 60 = 2²·3·5, but 12 ∤ 18 = 2·3² (needs 2², has only 2¹)." },
    ],
  },
  {
    id: "st-sets-operations",
    module: "m2",
    title: "Sets & Set Operations",
    cards: [
      { id: "st-so-subset", q: "A ⊆ B (A is a subset of B) means…", a: "every element of A is also in B",
        distractors: ["A and B have the same elements", "A has fewer elements than B", "some element of A is in B"],
        note: "A = B iff A ⊆ B and B ⊆ A." },
      { id: "st-so-union", q: "A ∪ B is the set of x such that…", a: "x ∈ A or x ∈ B",
        distractors: ["x ∈ A and x ∈ B", "x ∈ A and x ∉ B", "x ∉ A and x ∉ B"],
        note: "Union corresponds to logical OR." },
      { id: "st-so-inter", q: "A ∩ B is the set of x such that…", a: "x ∈ A and x ∈ B",
        distractors: ["x ∈ A or x ∈ B", "x ∈ A and x ∉ B", "x ∉ A or x ∉ B"],
        note: "Intersection corresponds to logical AND." },
      { id: "st-so-diff", q: "A ∖ B (set difference) is the set of x such that…", a: "x ∈ A and x ∉ B",
        distractors: ["x ∈ B and x ∉ A", "x ∈ A or x ∉ B", "x ∉ A and x ∉ B"],
        note: "\"in A but not in B.\"" },
      { id: "st-so-empty", q: "The empty set ∅ is…", a: "the set with no elements",
        distractors: ["the set containing 0", "the same as {∅}", "the universal set"],
        note: "|∅| = 0, but |{∅}| = 1." },
      { id: "st-so-power", q: "The power set P(A) is…", a: "the set of all subsets of A",
        distractors: ["the set A raised to a power", "the largest element of A", "A × A"],
        note: "|P(A)| = 2^|A|." },
    ],
  },
  {
    id: "st-sets-logic",
    module: "m2",
    title: "The Sets–Logic Correspondence & Set Proofs",
    cards: [
      { id: "st-sl-corr", q: "Under the sets–logic correspondence, A ∩ B matches which connective?", a: "∧ (and)",
        distractors: ["∨ (or)", "¬ (not)", "→ (implies)"],
        note: "∪↔∨, ∩↔∧, complement↔¬." },
      { id: "st-sl-demorgan", q: "De Morgan's logic law becomes which set identity?", a: "(A ∪ B)‾ = Ā ∩ B̄",
        distractors: ["(A ∪ B)‾ = Ā ∪ B̄", "(A ∩ B)‾ = Ā ∩ B̄", "A ∪ B = Ā ∩ B̄"],
        note: "¬(P ∨ Q) ≡ ¬P ∧ ¬Q translated to sets." },
      { id: "st-sl-why", q: "Why does every logical identity give a set identity?", a: "membership in a compound set is a logical statement about x",
        distractors: ["sets and propositions are literally the same thing", "it's a coincidence", "only De Morgan's laws transfer"],
        note: "The correspondence turns set operations into connectives." },
      { id: "st-sl-mutual", q: "The mutual-containment method proves A = B by showing…", a: "A ⊆ B and B ⊆ A",
        distractors: ["A ∩ B = ∅", "|A| = |B|", "A ∪ B = A"],
        note: "Each containment is a direct proof about an arbitrary element." },
      { id: "st-sl-subset", q: "To prove A ⊆ B, you…", a: "let x be an arbitrary element of A and show x ∈ B",
        distractors: ["exhibit one element of both A and B", "show |A| ≤ |B|", "assume A = B"],
        note: "Hypothesis x ∈ A, conclusion x ∈ B." },
      { id: "st-sl-iff", q: "In the if-and-only-if chain method, every step must be…", a: "an \"iff\" (↔), not just an implication",
        distractors: ["a one-way implication", "an inequality", "a set difference"],
        note: "Expand definitions to logic, apply equivalences, repackage." },
    ],
  },
  {
    id: "st-cardinality",
    module: "m2",
    title: "Cardinality, Inclusion–Exclusion & the Product Rule",
    cards: [
      { id: "st-card-nested", q: "What is |{{2, 4, 6}}|?", a: "1",
        distractors: ["3", "0", "6"],
        note: "One element, which happens to be a set. |{2,4,6}| = 3." },
      { id: "st-card-incexc", q: "Inclusion–Exclusion: |A ∪ B| = ?", a: "|A| + |B| − |A ∩ B|",
        distractors: ["|A| + |B|", "|A| + |B| + |A ∩ B|", "|A| · |B|"],
        note: "Subtract the double-counted overlap." },
      { id: "st-card-product", q: "The Product Rule gives |A × B| = ?", a: "|A| · |B|",
        distractors: ["|A| + |B|", "2^(|A|·|B|)", "|A| − |B|"],
        note: "Each ordered pair: one from A, one from B." },
      { id: "st-card-power", q: "The size of the power set is |P(A)| = ?", a: "2^|A|",
        distractors: ["|A|²", "2·|A|", "|A|!"],
        note: "Each element is independently in or out of a subset." },
      { id: "st-card-check", q: "If |A| = 5, then |P(A)| = ?", a: "32",
        distractors: ["25", "10", "16"],
        note: "2^5 = 32." },
    ],
  },
  {
    id: "rf-relations-functions",
    module: "m2",
    title: "Binary Relations & Functions",
    cards: [
      { id: "rf-rel-def", q: "A binary relation from A to B is…", a: "a subset of A × B (a set of ordered pairs)",
        distractors: ["a subset of A ∪ B", "a function from A to B", "an element of A × B"],
        note: "Relations generalize mappings between sets." },
      { id: "rf-func-def", q: "A function f : A → B is a relation with the extra property that…", a: "every element of A maps to exactly one element of B",
        distractors: ["every element of B is hit", "A and B are the same set", "no two inputs share an output"],
        note: "Functions are a special case of relations." },
      { id: "rf-domain", q: "In f : A → B, the set A is the… and B is the…", a: "domain; codomain",
        distractors: ["codomain; domain", "image; preimage", "range; domain"],
        note: "The domain is the inputs, the codomain the allowed outputs." },
      { id: "rf-bubble", q: "A bubble (arrow) diagram lets you…", a: "read off properties like injectivity and surjectivity at a glance",
        distractors: ["compute a derivative", "list every subset of A", "factor a number"],
        note: "Domain on the left, codomain on the right, arrows for related pairs." },
    ],
  },
  {
    id: "rf-function-properties",
    module: "m2",
    title: "Proving Function Properties",
    cards: [
      { id: "rf-inj-def", q: "A function is injective (one-to-one) when…", a: "different inputs give different outputs",
        distractors: ["every output is hit", "it has an inverse relation", "the domain equals the codomain"],
        note: "Equivalently f(x₁) = f(x₂) ⟹ x₁ = x₂." },
      { id: "rf-prove-inj", q: "To prove f is injective, you…", a: "assume f(x₁) = f(x₂) for arbitrary x₁, x₂ and show x₁ = x₂",
        distractors: ["exhibit one x with f(x) = y", "assume x₁ ≠ x₂ and stop", "show every y has a preimage"],
        note: "A direct proof of f(x₁) = f(x₂) → x₁ = x₂." },
      { id: "rf-prove-surj", q: "To prove f is surjective, you…", a: "let y be an arbitrary codomain element and exhibit an x with f(x) = y",
        distractors: ["assume f(x₁) = f(x₂) and show x₁ = x₂", "show the domain is infinite", "check one specific value"],
        note: "Often: solve f(x) = y for x, then verify x is in the domain." },
      { id: "rf-prove-bij", q: "To prove f is bijective, you…", a: "prove injective and surjective separately",
        distractors: ["prove only injective", "prove only surjective", "show the domain and codomain are equal"],
        note: "Two sub-proofs." },
      { id: "rf-parallel", q: "Proving surjectivity parallels which sets-segment proof?", a: "proving A ⊆ B — pick an arbitrary element and show a property",
        distractors: ["proving A ∩ B = ∅", "computing |P(A)|", "the inclusion–exclusion count"],
        note: "The \"pick an arbitrary element\" pattern keeps appearing." },
    ],
  },
  {
    id: "rf-composition",
    module: "m2",
    title: "Function Composition",
    cards: [
      { id: "rf-comp-def", q: "For f : A → B and g : B → C, (g ∘ f)(x) = ?", a: "g(f(x))",
        distractors: ["f(g(x))", "g(x) · f(x)", "f(x) + g(x)"],
        note: "g ∘ f : A → C." },
      { id: "rf-comp-order", q: "g ∘ f means…", a: "first apply f, then apply g",
        distractors: ["first apply g, then apply f", "apply f and g simultaneously", "apply whichever is injective first"],
        note: "The notation order is the reverse of the application order — a common error." },
      { id: "rf-comp-when", q: "You can form g ∘ f exactly when…", a: "the codomain of f matches the domain of g",
        distractors: ["f and g have the same domain", "f and g are both injective", "the domains are disjoint"],
        note: "The functions must \"chain together.\"" },
      { id: "rf-comp-preserve", q: "If f and g are both injective, then g ∘ f is…", a: "injective",
        distractors: ["surjective but not injective", "neither", "bijective automatically"],
        note: "Composition preserves injectivity and surjectivity separately." },
    ],
  },
  {
    id: "rf-proof-review",
    module: "m2",
    title: "Proof Review as a Learning Tool",
    cards: [
      { id: "rf-review-why", q: "Why is critically reading others' proofs useful?", a: "it activates a different attention that catches errors you'd gloss over in your own work",
        distractors: ["it's faster than writing proofs", "it replaces learning the definitions", "it guarantees your proofs are correct"],
        note: "You notice logic errors, gaps, and style issues." },
      { id: "rf-review-quant", q: "Which is a key thing to check when reviewing a proof?", a: "are the quantifiers (∀ vs. ∃) correct and in the right order?",
        distractors: ["is the proof at least one page long?", "does it use fancy notation?", "does it avoid all examples?"],
        note: "Also: does each step follow, is notation consistent, is it precise (no hand-waving)?" },
    ],
  },
  {
    id: "tk-rational-irrational",
    module: "toolkit",
    title: "Rational & Irrational Numbers",
    cards: [
      { id: "tk-ri-def", q: "x is rational exactly when…", a: "x = p/q for integers p, q with q ≠ 0",
        distractors: ["x has a finite decimal", "x is positive and whole", "x = √n for some n"],
        note: "Irrational = real but not rational." },
      { id: "tk-ri-closed", q: "The rationals are closed under…", a: "addition, subtraction, multiplication, and division by nonzero",
        distractors: ["only addition and subtraction", "square roots", "no operations"],
        note: "A sum/product of rationals is rational." },
      { id: "tk-ri-sum", q: "rational + irrational = ?", a: "irrational",
        distractors: ["rational", "could be either", "always zero"],
        note: "If it were rational, the irrational would be a difference of rationals." },
      { id: "tk-ri-prod", q: "(nonzero rational) × irrational = ?", a: "irrational",
        distractors: ["rational", "could be either", "always irrational, even times zero"],
        note: "Zero times an irrational is rational — hence 'nonzero'." },
      { id: "tk-ri-sqrt2", q: "The standard proof that √2 is irrational is by…", a: "contradiction: assume p/q in lowest terms, derive both p, q even",
        distractors: ["induction on q", "a direct construction", "the pigeonhole principle"],
        note: "p² = 2q² forces a common factor of 2." },
      { id: "tk-ri-density", q: "Between any two distinct reals there is…", a: "a rational number",
        distractors: ["no rational number", "exactly one integer", "only irrationals"],
        note: "The rationals are dense in ℝ." },
    ],
  },
  {
    id: "tk-summations",
    module: "toolkit",
    title: "Summation Formulas",
    cards: [
      { id: "tk-sm-nn1", q: "1 + 2 + … + n = ?", a: "n(n + 1) / 2",
        distractors: ["n² / 2", "n(n − 1) / 2", "(n + 1)² / 2"],
        note: "Pair terms from both ends." },
      { id: "tk-sm-odd", q: "1 + 3 + 5 + … + (2n − 1) = ?", a: "n²",
        distractors: ["n(n + 1) / 2", "2n − 1", "n(2n − 1)"],
        note: "The sum of the first n odd numbers is a perfect square." },
      { id: "tk-sm-squares", q: "1² + 2² + … + n² = ?", a: "n(n + 1)(2n + 1) / 6",
        distractors: ["(n(n + 1) / 2)²", "n³ / 3", "n(n + 1) / 2"],
        note: "" },
      { id: "tk-sm-cubes", q: "1³ + 2³ + … + n³ = ?", a: "(n(n + 1) / 2)²",
        distractors: ["n(n + 1)(2n + 1) / 6", "n⁴ / 4", "n²(n + 1)"],
        note: "The square of the first-n sum." },
      { id: "tk-sm-geom", q: "1 + r + r² + … + rⁿ = ? (r ≠ 1)", a: "(rⁿ⁺¹ − 1) / (r − 1)",
        distractors: ["rⁿ / (r − 1)", "n·rⁿ", "(rⁿ − 1) / r"],
        note: "Geometric series closed form." },
    ],
  },
  {
    id: "tk-inequalities",
    module: "toolkit",
    title: "Inequalities & Order",
    cards: [
      { id: "tk-in-triangle", q: "The triangle inequality states…", a: "|a + b| ≤ |a| + |b|",
        distractors: ["|a + b| ≥ |a| + |b|", "|a + b| = |a| + |b|", "|a − b| ≤ |a| − |b|"],
        note: "" },
      { id: "tk-in-reverse", q: "The reverse triangle inequality bounds…", a: "| |a| − |b| | ≤ |a − b|",
        distractors: ["|a| − |b| ≥ |a − b|", "|a + b| ≤ |a| − |b|", "|ab| ≤ |a| + |b|"],
        note: "" },
      { id: "tk-in-amgm", q: "AM–GM for a, b ≥ 0 says…", a: "(a + b)/2 ≥ √(ab)",
        distractors: ["(a + b)/2 ≤ √(ab)", "a + b ≥ ab", "√(a + b) ≥ a·b"],
        note: "Equality iff a = b." },
      { id: "tk-in-bernoulli", q: "Bernoulli's inequality: for x ≥ −1, n ∈ ℕ…", a: "(1 + x)ⁿ ≥ 1 + nx",
        distractors: ["(1 + x)ⁿ ≤ 1 + nx", "(1 + x)ⁿ = 1 + nx", "(1 + nx)ⁿ ≥ 1 + x"],
        note: "" },
      { id: "tk-in-trans", q: "From a ≤ b and b ≤ c you conclude…", a: "a ≤ c",
        distractors: ["a < c strictly", "c ≤ a", "nothing"],
        note: "≤ is transitive." },
    ],
  },
  {
    id: "tk-floor-ceiling",
    module: "toolkit",
    title: "Floor & Ceiling",
    cards: [
      { id: "tk-fc-floordef", q: "⌊x⌋ is…", a: "the greatest integer ≤ x",
        distractors: ["the least integer ≥ x", "x rounded to the nearest integer", "x with its decimals dropped only if x > 0"],
        note: "⌈x⌉ is the least integer ≥ x." },
      { id: "tk-fc-char", q: "⌊x⌋ = n (n an integer) is equivalent to…", a: "n ≤ x < n + 1",
        distractors: ["n − 1 < x ≤ n", "n < x < n + 1", "x = n exactly"],
        note: "Ceiling: n − 1 < x ≤ n." },
      { id: "tk-fc-ceilfromfloor", q: "⌈x⌉ equals…", a: "−⌊−x⌋",
        distractors: ["⌊x⌋ + 1 always", "−⌊x⌋", "⌊x + 1⌋"],
        note: "Reflect, floor, reflect back." },
      { id: "tk-fc-multiples", q: "How many integers in 1..n are divisible by m?", a: "⌊n / m⌋",
        distractors: ["⌈n / m⌉", "n / m exactly", "n − m"],
        note: "Counting multiples with the floor." },
    ],
  },
  {
    id: "tk-principles",
    module: "toolkit",
    title: "Foundational Principles",
    cards: [
      { id: "tk-pr-wop", q: "The Well-Ordering Principle states…", a: "every nonempty subset of ℕ has a least element",
        distractors: ["every subset of ℤ has a least element", "ℕ has a largest element", "every set can be ordered"],
        note: "Underlies induction and 'smallest counterexample' proofs." },
      { id: "tk-pr-induction", q: "Ordinary induction proves ∀n P(n) from…", a: "P(0) and P(k) → P(k+1)",
        distractors: ["P(0) only", "P(n) for one large n", "P(k+1) → P(k)"],
        note: "Base case plus inductive step." },
      { id: "tk-pr-strong", q: "Strong induction differs by assuming…", a: "P holds for all values up to k, to prove P(k+1)",
        distractors: ["only P(k) to prove P(k+1)", "P(k+1) to prove P(k)", "nothing in the step"],
        note: "Useful when P(k+1) depends on earlier cases." },
      { id: "tk-pr-pigeon", q: "The Pigeonhole Principle: n items in k boxes with n > k forces…", a: "some box with ≥ 2 items",
        distractors: ["every box with ≥ 2 items", "an empty box", "exactly one full box"],
        note: "" },
      { id: "tk-pr-genpigeon", q: "Generalized Pigeonhole: n items in k boxes forces some box with at least…", a: "⌈n / k⌉ items",
        distractors: ["⌊n / k⌋ items", "n − k items", "n / k items exactly"],
        note: "" },
    ],
  },
  {
    id: "tk-counting-binomial",
    module: "toolkit",
    title: "Counting, Functions & the Binomial Theorem",
    cards: [
      { id: "tk-cb-product", q: "|A × B| equals…", a: "|A| · |B|",
        distractors: ["|A| + |B|", "|A| − |B|", "max(|A|, |B|)"],
        note: "The product rule." },
      { id: "tk-cb-incexc", q: "Inclusion–exclusion for two sets: |A ∪ B| = ?", a: "|A| + |B| − |A ∩ B|",
        distractors: ["|A| + |B|", "|A| + |B| + |A ∩ B|", "|A| · |B|"],
        note: "Subtract the double-counted overlap." },
      { id: "tk-cb-injective", q: "A function f is injective (one-to-one) when…", a: "f(x) = f(y) implies x = y",
        distractors: ["every codomain element is hit", "it has an inverse image for all y", "f(x) = x"],
        note: "Surjective = onto (every output hit)." },
      { id: "tk-cb-comp", q: "If f and g are both surjective, then g∘f is…", a: "surjective",
        distractors: ["injective but not surjective", "neither", "bijective automatically"],
        note: "Composition preserves injectivity and surjectivity separately." },
      { id: "tk-cb-binomial", q: "The Binomial Theorem expands (x + y)ⁿ as…", a: "Σₖ C(n, k) xᵏ yⁿ⁻ᵏ",
        distractors: ["Σₖ C(n, k) xᵏ", "n·(x + y)", "xⁿ + yⁿ"],
        note: "" },
      { id: "tk-cb-pascal", q: "Pascal's Rule states C(n, k) = ?", a: "C(n − 1, k − 1) + C(n − 1, k)",
        distractors: ["C(n − 1, k) − C(n − 1, k − 1)", "C(n, k − 1) + C(n, k + 1)", "n · C(n − 1, k)"],
        note: "Each entry is the sum of the two above it." },
      { id: "tk-cb-rowsum", q: "Σₖ₌₀ⁿ C(n, k) = ?", a: "2ⁿ",
        distractors: ["n²", "n!", "2n"],
        note: "The number of subsets of an n-element set." },
    ],
  },
  {
    id: "logical-forms",
    module: "m1",
    title: "Logical Forms",
    cards: [
      {
        id: "lf-converse",
        q: "What is the converse of P → Q?",
        a: "Q → P",
        distractors: ["¬P → ¬Q", "¬Q → ¬P", "¬(P → Q)"],
        note: "Converse — swap the two sides.",
      },
      {
        id: "lf-inverse",
        q: "What is the inverse of P → Q?",
        a: "¬P → ¬Q",
        distractors: ["Q → P", "¬Q → ¬P", "P → ¬Q"],
        note: "Inverse — negate both sides.",
      },
      {
        id: "lf-contrapositive",
        q: "What is the contrapositive of P → Q?",
        a: "¬Q → ¬P",
        distractors: ["Q → P", "¬P → ¬Q", "P ∧ ¬Q"],
        note: "Contrapositive — swap and negate. It is equivalent to the original.",
      },
      {
        id: "lf-equivalent",
        q: "Which of these is logically equivalent to P → Q?",
        a: "The contrapositive, ¬Q → ¬P",
        distractors: ["The converse, Q → P", "The inverse, ¬P → ¬Q", "None of them"],
        note: "Only the contrapositive is equivalent. The converse and inverse are equivalent to each other, but not to the original.",
      },
      {
        id: "lf-converse-inverse",
        q: "The converse and the inverse of an implication are equivalent to…",
        a: "each other (but not to the original)",
        distractors: ["the original implication", "the contrapositive", "nothing — all four differ"],
        note: "Converse (Q → P) and inverse (¬P → ¬Q) are contrapositives of each other, so they match.",
      },
      {
        id: "lf-concrete-contrapositive",
        q: "Contrapositive of \"If it rains (R), then the ground is wet (W)\"?",
        a: "If the ground is not wet, then it is not raining (¬W → ¬R)",
        distractors: [
          "If the ground is wet, then it is raining (W → R)",
          "If it is not raining, then the ground is not wet (¬R → ¬W)",
          "It is raining and the ground is not wet (R ∧ ¬W)",
        ],
        note: "Contrapositive swaps and negates — and it's equivalent to the original.",
      },
      {
        id: "lf-concrete-converse",
        q: "Converse of \"If n is divisible by 4 (D), then n is even (E)\"?",
        a: "If n is even, then n is divisible by 4 (E → D)",
        distractors: [
          "If n is divisible by 4, then n is even (D → E)",
          "If n is not even, then n is not divisible by 4 (¬E → ¬D)",
          "If n is not divisible by 4, then n is not even (¬D → ¬E)",
        ],
        note: "Converse just swaps the two sides — and note this converse is false, so a converse need not hold.",
      },
      {
        id: "lf-neg-implication",
        q: "The negation of P → Q, i.e. ¬(P → Q), is equivalent to…",
        a: "P ∧ ¬Q",
        distractors: ["¬P ∧ Q", "¬P ∨ ¬Q", "¬Q → ¬P"],
        note: "Since P → Q ≡ ¬P ∨ Q, its negation is P ∧ ¬Q — the one case that breaks the implication.",
      },
      {
        id: "lf-which-not-equivalent",
        q: "Which form is NOT equivalent to P → Q?",
        a: "The converse Q → P",
        distractors: ["The contrapositive ¬Q → ¬P", "¬P ∨ Q", "Its own double negation"],
        note: "The converse is the classic mistake — only the contrapositive is equivalent.",
      },
      {
        id: "lf-inverse-of-contrapositive",
        q: "Which pair are equivalent to each other?",
        a: "Converse (Q → P) and inverse (¬P → ¬Q)",
        distractors: [
          "Converse (Q → P) and contrapositive (¬Q → ¬P)",
          "Original (P → Q) and converse (Q → P)",
          "Inverse (¬P → ¬Q) and contrapositive (¬Q → ¬P)",
        ],
        note: "Original ≡ contrapositive; converse ≡ inverse. The two groups are not equivalent to each other.",
      },
    ],
  },

  {
    id: "equivalence-laws",
    module: "m1",
    title: "Equivalence Laws",
    cards: [
      {
        id: "eq-commutative",
        q: "Which law says P ∧ Q ≡ Q ∧ P?",
        a: "Commutative",
        distractors: ["Associative", "Distributive", "De Morgan"],
        note: "Commutative — order doesn't matter (holds for ∧ and ∨).",
      },
      {
        id: "eq-associative",
        q: "Which law says (P ∧ Q) ∧ R ≡ P ∧ (Q ∧ R)?",
        a: "Associative",
        distractors: ["Commutative", "Distributive", "Double negation"],
        note: "Associative — grouping doesn't matter (holds for ∧ and ∨).",
      },
      {
        id: "eq-distributive-and",
        q: "Distribute: P ∧ (Q ∨ R) ≡ ?",
        a: "(P ∧ Q) ∨ (P ∧ R)",
        distractors: ["(P ∨ Q) ∧ (P ∨ R)", "(P ∧ Q) ∨ R", "P ∨ (Q ∧ R)"],
        note: "Distributive — ∧ distributes over ∨.",
      },
      {
        id: "eq-distributive-or",
        q: "Distribute: P ∨ (Q ∧ R) ≡ ?",
        a: "(P ∨ Q) ∧ (P ∨ R)",
        distractors: ["(P ∧ Q) ∨ (P ∧ R)", "(P ∨ Q) ∨ R", "P ∧ (Q ∨ R)"],
        note: "Distributive — ∨ distributes over ∧.",
      },
      {
        id: "eq-demorgan-and",
        q: "By De Morgan's law, ¬(P ∧ Q) ≡ ?",
        a: "¬P ∨ ¬Q",
        distractors: ["¬P ∧ ¬Q", "¬(P ∨ Q)", "P ∨ Q"],
        note: "A negation over ∧ flips it to ∨ and negates each part.",
      },
      {
        id: "eq-demorgan-or",
        q: "By De Morgan's law, ¬(P ∨ Q) ≡ ?",
        a: "¬P ∧ ¬Q",
        distractors: ["¬P ∨ ¬Q", "¬(P ∧ Q)", "P ∧ Q"],
        note: "A negation over ∨ flips it to ∧ and negates each part.",
      },
      {
        id: "eq-double-negation",
        q: "Double negation: ¬(¬P) ≡ ?",
        a: "P",
        distractors: ["¬P", "P ∨ ¬P", "P ∧ ¬P"],
        note: "Two negations cancel.",
      },
      {
        id: "eq-implication",
        q: "Rewrite the implication P → Q without → (implication law).",
        a: "¬P ∨ Q",
        distractors: ["P ∨ ¬Q", "¬P ∧ Q", "¬Q → ¬P"],
        note: "Implication law — the key step for eliminating →.",
      },
      {
        id: "eq-biconditional",
        q: "Expand the biconditional P ↔ Q.",
        a: "(P → Q) ∧ (Q → P)",
        distractors: ["(P → Q) ∨ (Q → P)", "(P ∧ Q) ∨ (¬P ∧ ¬Q)", "¬P ∨ Q"],
        note: "P ↔ Q means both directions hold. (It also equals (P ∧ Q) ∨ (¬P ∧ ¬Q).)",
      },
      {
        id: "eq-xor",
        q: "Expand exclusive or, P ⊕ Q, into ∧/∨/¬.",
        a: "(P ∧ ¬Q) ∨ (¬P ∧ Q)",
        distractors: ["(P ∧ Q) ∨ (¬P ∧ ¬Q)", "(P ∨ Q) ∧ (P ∧ Q)", "¬P ∨ ¬Q"],
        note: "XOR is true when exactly one holds. Also (P ∨ Q) ∧ ¬(P ∧ Q).",
      },
      {
        id: "eq-demorgan-reverse",
        q: "Which law rewrites ¬P ∧ ¬Q as ¬(P ∨ Q)?",
        a: "De Morgan",
        distractors: ["Distributive", "Commutative", "Double negation"],
        note: "De Morgan works both directions: ¬P ∧ ¬Q ≡ ¬(P ∨ Q).",
      },
      {
        id: "eq-demorgan-three",
        q: "By De Morgan's law, ¬(P ∧ Q ∧ R) ≡ ?",
        a: "¬P ∨ ¬Q ∨ ¬R",
        distractors: ["¬P ∧ ¬Q ∧ ¬R", "¬(P ∨ Q ∨ R)", "P ∨ Q ∨ R"],
        note: "Negating a chain of ∧ flips every one to ∨ and negates each term.",
      },
      {
        id: "eq-implication-reverse",
        q: "Which single expression is equivalent to ¬A ∨ B?",
        a: "A → B",
        distractors: ["B → A", "A ∧ B", "¬(A → B)"],
        note: "Implication law read backward: ¬A ∨ B ≡ A → B.",
      },
      {
        id: "eq-contrapositive-implication",
        q: "Applying the implication law to ¬Q → ¬P gives…",
        a: "Q ∨ ¬P",
        distractors: ["¬Q ∨ P", "¬P ∨ Q", "P ∧ ¬Q"],
        note: "¬Q → ¬P ≡ ¬(¬Q) ∨ ¬P ≡ Q ∨ ¬P — which is also ¬P ∨ Q, matching P → Q.",
      },
      {
        id: "eq-distributive-invalid",
        q: "Which of these is NOT a valid equivalence?",
        a: "P ∨ (Q ∧ R) ≡ (P ∨ Q) ∧ R",
        distractors: [
          "P ∧ (Q ∨ R) ≡ (P ∧ Q) ∨ (P ∧ R)",
          "P ∨ (Q ∧ R) ≡ (P ∨ Q) ∧ (P ∨ R)",
          "P ∧ (Q ∧ R) ≡ (P ∧ Q) ∧ R",
        ],
        note: "You must distribute over BOTH terms; dropping one (…∧ R) is a classic error.",
      },
      {
        id: "eq-commutative-which",
        q: "Which rewrite uses ONLY the commutative law?",
        a: "(A ∨ B) ≡ (B ∨ A)",
        distractors: [
          "(A ∨ B) ∧ (A ∨ C) ≡ A ∨ (B ∧ C)",
          "¬(A ∧ B) ≡ ¬A ∨ ¬B",
          "(A ∧ B) ∧ C ≡ A ∧ (B ∧ C)",
        ],
        note: "Commutative only swaps operand order; the others are distributive, De Morgan, associative.",
      },
      {
        id: "eq-associative-which",
        q: "(A ∨ B) ∨ C ≡ A ∨ (B ∨ C) is an instance of which law?",
        a: "Associative",
        distractors: ["Commutative", "Distributive", "De Morgan"],
        note: "Associative regroups the same operator; order of operands is unchanged.",
      },
      {
        id: "eq-double-neg-apply",
        q: "Simplify ¬¬¬P using double negation.",
        a: "¬P",
        distractors: ["P", "¬¬P", "P ∨ ¬P"],
        note: "Three negations cancel in pairs, leaving one: ¬¬¬P ≡ ¬P.",
      },
      {
        id: "eq-biconditional-false-when",
        q: "P ↔ Q is TRUE exactly when…",
        a: "P and Q have the same truth value",
        distractors: [
          "P and Q have different truth values",
          "at least one of P, Q is true",
          "both P and Q are true",
        ],
        note: "A biconditional holds when both sides agree; XOR is its opposite.",
      },
      {
        id: "eq-xor-vs-bicond",
        q: "P ⊕ Q is the negation of which connective?",
        a: "P ↔ Q",
        distractors: ["P ∧ Q", "P ∨ Q", "P → Q"],
        note: "XOR is true exactly when the biconditional is false — they are negations of each other.",
      },
    ],
  },

  {
    id: "inference-rules",
    module: "m1",
    title: "Inference Rules",
    cards: [
      {
        id: "inf-modus-ponens",
        q: "From A and A → B, what can you conclude (modus ponens)?",
        a: "B",
        distractors: ["¬A", "¬B", "A ∧ B"],
        note: "Modus ponens — the engine of forward reasoning.",
      },
      {
        id: "inf-modus-tollens",
        q: "From ¬B and A → B, what can you conclude (modus tollens)?",
        a: "¬A",
        distractors: ["¬B", "B", "A"],
        note: "Modus tollens — modus ponens on the contrapositive ¬B → ¬A.",
      },
      {
        id: "inf-mt-name",
        q: "Which rule lets you conclude ¬A from ¬B and A → B?",
        a: "Modus tollens",
        distractors: ["Modus ponens", "And-elimination", "De Morgan"],
        note: "Modus tollens reasons backward from a false consequent.",
      },
      {
        id: "inf-and-elimination",
        q: "From A ∧ B, what does and-elimination let you conclude?",
        a: "A (and likewise B)",
        distractors: ["A ∨ B", "only A, never B", "A → B"],
        note: "If both are true you can conclude either one alone.",
      },
      {
        id: "inf-mp-concrete",
        q: "Given \"If it's a weekday, the library is open\" and \"It's a weekday,\" conclude…",
        a: "The library is open",
        distractors: ["It's not a weekday", "The library is closed", "It's a weekday and the library is open"],
        note: "Modus ponens applied to a concrete argument.",
      },
      {
        id: "inf-mt-concrete",
        q: "Given \"If it's a weekday, the library is open\" and \"The library is NOT open,\" conclude…",
        a: "It's not a weekday",
        distractors: ["It's a weekday", "The library is open", "Nothing can be concluded"],
        note: "Modus tollens: deny the consequent to deny the antecedent.",
      },
      {
        id: "inf-affirming-consequent",
        q: "From A → B and B, concluding A is…",
        a: "invalid — the fallacy of affirming the consequent",
        distractors: ["valid — modus ponens", "valid — modus tollens", "valid — and-elimination"],
        note: "B being true doesn't force A; something else could make B true.",
      },
      {
        id: "inf-denying-antecedent",
        q: "From A → B and ¬A, concluding ¬B is…",
        a: "invalid — the fallacy of denying the antecedent",
        distractors: ["valid — modus tollens", "valid — modus ponens", "valid — contrapositive"],
        note: "¬A doesn't force ¬B; B might hold for another reason.",
      },
      {
        id: "inf-mp-pattern",
        q: "Which argument pattern is modus ponens?",
        a: "A, A → B ⊢ B",
        distractors: ["¬B, A → B ⊢ ¬A", "A ∧ B ⊢ A", "A → B, B ⊢ A"],
        note: "Affirm the antecedent to get the consequent.",
      },
      {
        id: "inf-and-elim-both",
        q: "From (P ∨ Q) ∧ R, and-elimination lets you conclude…",
        a: "R (and also P ∨ Q)",
        distractors: ["P", "Q", "P ∧ Q"],
        note: "And-elimination splits the top-level ∧ into either conjunct — here (P ∨ Q) or R.",
      },
    ],
  },

  {
    id: "direct-proofs",
    module: "m1",
    title: "Direct Proofs",
    cards: [
      {
        id: "dp-engine",
        q: "Which inference rules drive a direct proof?",
        a: "Modus ponens and modus tollens",
        distractors: ["De Morgan's laws", "Distribution and association", "Universal and existential instantiation only"],
        note: "A direct proof reasons forward, step by justified step.",
      },
      {
        id: "dp-strategy-universal",
        q: "To prove a universal claim ∀x. P(x) directly, you…",
        a: "let x be an arbitrary element of the domain and show P(x)",
        distractors: ["exhibit one specific x and verify P(x)", "find a counterexample", "assume P(x) and derive a contradiction"],
        note: "Arbitrary x ⇒ the argument works for every element.",
      },
      {
        id: "dp-strategy-implication",
        q: "To prove an implication P → Q directly, you…",
        a: "assume P, then deduce Q",
        distractors: ["assume Q, then deduce P", "assume ¬P, then deduce ¬Q", "show P and Q are both true"],
        note: "Assume the antecedent; reach the consequent.",
      },
      {
        id: "dp-strategy-existential",
        q: "To prove an existential claim ∃x. P(x) directly, you…",
        a: "exhibit a specific x and verify P(x)",
        distractors: ["let x be arbitrary and show P(x)", "show P(x) fails for some x", "assume ¬∃x. P(x)"],
        note: "One witness is enough.",
      },
      {
        id: "dp-strategy-neg-universal",
        q: "To prove ¬∀x. P(x), the cleanest strategy is to…",
        a: "find a counterexample: a specific x where P(x) fails",
        distractors: ["let x be arbitrary and show P(x)", "exhibit an x where P(x) holds", "prove ∀x. P(x) first"],
        note: "¬∀x. P(x) ≡ ∃x. ¬P(x) — a single counterexample suffices.",
      },
      {
        id: "dp-checklist-first",
        q: "What is the FIRST step of the direct-proof checklist?",
        a: "Identify the givens (what you may assume)",
        distractors: ["Write the proof", "Pick a proof strategy", "Explore with examples"],
        note: "Start by writing down what you're given.",
      },
      {
        id: "dp-concrete-even",
        q: "To prove \"if n is even, then n² is even,\" your first move is to…",
        a: "assume n is even (so n = 2k) and derive that n² is even",
        distractors: [
          "assume n² is even and derive that n is even",
          "try n = 2, 4, 6 and observe the pattern",
          "assume n is odd and reach a contradiction",
        ],
        note: "It's an implication — assume the antecedent, unfold the definition, reach the consequent.",
      },
      {
        id: "dp-arbitrary-vs-specific",
        q: "You prove ∀x with an arbitrary x, but ∃x with a specific x. Why arbitrary for ∀?",
        a: "An argument about an arbitrary element applies to every element",
        distractors: [
          "Because ∀ only needs one example",
          "Because arbitrary elements are easier to compute with",
          "Because ∃ is harder to prove than ∀",
        ],
        note: "Arbitrary = 'I assumed nothing special,' so the conclusion holds for all.",
      },
      {
        id: "dp-assume-what",
        q: "To directly prove \"If a and b are odd, then a + b is even,\" you assume…",
        a: "a and b are both odd",
        distractors: ["a + b is even", "a + b is odd", "a is odd and b is even"],
        note: "Assume the full antecedent (both odd), then compute a + b.",
      },
      {
        id: "dp-gather-definitions",
        q: "Why does the checklist say to write down formal definitions (even, rational, divides)?",
        a: "Definitions give you variables and structure to work with",
        distractors: [
          "To make the proof look longer",
          "Because definitions are the conclusion",
          "So you can skip choosing a strategy",
        ],
        note: "\"n is even\" becomes \"n = 2k\" — now you have algebra to manipulate.",
      },
      {
        id: "dp-neg-universal-concrete",
        q: "To disprove \"every prime is odd,\" the cleanest approach is to…",
        a: "give the counterexample 2 (prime and even)",
        distractors: [
          "assume a prime p is arbitrary and show it's odd",
          "list the first ten primes",
          "prove all primes are odd first",
        ],
        note: "Disproving a universal = producing one counterexample.",
      },
      {
        id: "dp-last-step",
        q: "What is the LAST step of the checklist?",
        a: "Write the proof: state the claim, introduce variables, reason, conclude",
        distractors: ["Identify the givens", "Explore with examples", "Pick a strategy"],
        note: "Everything before it is scratch work; writing is the final step.",
      },
      {
        id: "dp-combine-strategies",
        q: "For ∀x. (P(x) → Q(x)), you combine which two strategies?",
        a: "Universal (arbitrary x), then implication (assume P(x), show Q(x))",
        distractors: [
          "Existential, then implication",
          "Counterexample, then universal",
          "Implication only",
        ],
        note: "Nested logical forms mean nested strategies: outer ∀, inner →.",
      },
    ],
  },

  {
    id: "proof-by-cases",
    module: "m1",
    title: "Proof by Cases",
    cards: [
      {
        id: "pc-method",
        q: "What is the core idea of proof by cases?",
        a: "Split the domain into exhaustive cases, prove the claim in each, then conclude",
        distractors: [
          "Assume the claim is false and derive a contradiction",
          "Exhibit one example that satisfies the claim",
          "Prove the contrapositive instead",
        ],
        note: "Every element must fall into at least one case.",
      },
      {
        id: "pc-when",
        q: "Proof by cases is especially natural when the antecedent is…",
        a: "a disjunction — \"if A or B, then Q\"",
        distractors: [
          "a conjunction — \"if A and B, then Q\"",
          "an existential — \"if some x has P\"",
          "a single equation",
        ],
        note: "Prove Q assuming A, then prove Q assuming B.",
      },
      {
        id: "pc-exhaustive",
        q: "What does it mean for your cases to be \"exhaustive\"?",
        a: "Every element of the domain falls into at least one case",
        distractors: [
          "The cases don't overlap",
          "There are exactly two cases",
          "Each case is easy to prove",
        ],
        note: "Proving it for only some cases doesn't prove the claim.",
      },
      {
        id: "pc-missing-step",
        q: "After proving the claim in every case, what must you still do?",
        a: "Write a concluding sentence tying the cases together",
        distractors: [
          "Nothing — the last case finishes the proof",
          "Prove the contrapositive",
          "Find a counterexample",
        ],
        note: "\"Since the cases are exhaustive and the claim holds in each, the claim is proved.\"",
      },
      {
        id: "pc-division-mod3",
        q: "To prove a claim about divisibility by 3, the natural case split is…",
        a: "n mod 3 = 0, 1, or 2",
        distractors: ["even vs. odd", "positive vs. negative", "prime vs. composite"],
        note: "The three residues mod 3 are exhaustive for the integers.",
      },
      {
        id: "pc-parity",
        q: "Which case split fits a claim that behaves differently for even and odd integers?",
        a: "Even vs. odd",
        distractors: ["n mod 3 = 0, 1, 2", "positive, negative, zero", "n, n+1, n+2"],
        note: "Parity (even n = 2k, odd n = 2k+1) is exhaustive over the integers.",
      },
    ],
  },

  {
    id: "proving-uniqueness",
    module: "m1",
    title: "Proving Uniqueness",
    cards: [
      {
        id: "pu-meaning",
        q: "What does ∃!y. P(y) assert?",
        a: "Existence AND uniqueness — at least one y works, and at most one does",
        distractors: [
          "Only existence — at least one y works",
          "Only uniqueness — at most one y works",
          "That P(y) holds for every y",
        ],
        note: "∃! packs two claims: something exists, and it's the only one.",
      },
      {
        id: "pu-two-steps",
        q: "A uniqueness proof (∃!y. P(y)) has which two steps?",
        a: "Prove existence, then prove uniqueness",
        distractors: [
          "Prove existence twice",
          "Prove the claim and its contrapositive",
          "Split into cases and conclude",
        ],
        note: "Existence: exhibit a witness. Uniqueness: any two witnesses are equal.",
      },
      {
        id: "pu-existence",
        q: "How do you carry out the EXISTENCE step?",
        a: "Exhibit a specific value and verify it satisfies P",
        distractors: [
          "Assume two values and show they're equal",
          "Assume no value satisfies P and derive a contradiction",
          "Let the value be arbitrary",
        ],
        note: "It's just a standard existential proof — produce a witness.",
      },
      {
        id: "pu-uniqueness",
        q: "How do you carry out the UNIQUENESS step?",
        a: "Assume y₀ and y₁ both satisfy P, then show y₀ = y₁",
        distractors: [
          "Exhibit one value satisfying P",
          "Show P fails for all other values one by one",
          "Prove ∀y. P(y)",
        ],
        note: "If two things satisfy the property, they must be the same value.",
      },
      {
        id: "pu-assume",
        q: "In the uniqueness step, what are you allowed to assume?",
        a: "That both y₀ and y₁ satisfy P(y)",
        distractors: [
          "That y₀ ≠ y₁",
          "That only y₀ satisfies P",
          "That P has no witnesses",
        ],
        note: "Assume P(y₀) and P(y₁), then derive y₀ = y₁.",
      },
      {
        id: "pu-incomplete",
        q: "A proof shows k = 4 satisfies k + 3 = 7 and stops. What's missing?",
        a: "The uniqueness step — showing no other k works",
        distractors: [
          "The existence step",
          "A concluding sentence only",
          "Nothing — it's complete",
        ],
        note: "Existence alone doesn't establish ∃!; you must also show any such k equals 4.",
      },
    ],
  },

  {
    id: "predicates-quantifiers",
    module: "m1",
    title: "Predicates & Quantifiers",
    cards: [
      {
        id: "pq-predicate",
        q: "What is a predicate?",
        a: "A function from one or more domain values to a truth value, e.g. P(x)",
        distractors: ["A statement that is always true", "The domain of a formula", "A quantifier such as ∀ or ∃"],
        note: "A predicate with 0 inputs is just a proposition.",
      },
      {
        id: "pq-domain",
        q: "What does the domain (universe of discourse) specify?",
        a: "The set of objects the variables range over",
        distractors: ["The truth value of the predicate", "Which quantifier to use", "The order of the quantifiers"],
        note: "The same formula can be true over one domain and false over another.",
      },
      {
        id: "pq-forall-true",
        q: "∀x P(x) is TRUE exactly when…",
        a: "P(x) holds for every element of the domain",
        distractors: ["P(x) holds for at least one element", "P(x) holds for exactly one element", "P(x) fails for every element"],
        note: "Think of ∀ as a big AND. One counterexample makes it false.",
      },
      {
        id: "pq-exists-true",
        q: "∃x P(x) is TRUE exactly when…",
        a: "P(x) holds for at least one element of the domain",
        distractors: ["P(x) holds for every element", "P(x) holds for exactly one element", "P(x) fails for every element"],
        note: "Think of ∃ as a big OR. One witness makes it true.",
      },
      {
        id: "pq-unique",
        q: "What does ∃!x P(x) assert?",
        a: "There exists exactly one x such that P(x)",
        distractors: ["There exists at least one x such that P(x)", "For all x, P(x)", "There is no x such that P(x)"],
        note: "∃! = at least one and no more than one.",
      },
      {
        id: "pq-free-bound",
        q: "In ∀x P(x, y), which variable is free?",
        a: "y",
        distractors: ["x", "both x and y", "neither"],
        note: "x is bound by the quantifier; y is free. A formula with a free variable is still a predicate.",
      },
      {
        id: "pq-ground",
        q: "What is a ground formula?",
        a: "A formula with all variables replaced by specific domain values",
        distractors: ["A formula with a free variable", "A formula with all variables bound by quantifiers", "A predicate with no domain"],
        note: "A ground formula always evaluates to true or false — e.g. Even(4) ∧ Prime(4).",
      },
      {
        id: "pq-neg-forall",
        q: "Push the negation in: ¬∀x P(x) ≡ ?",
        a: "∃x ¬P(x)",
        distractors: ["∀x ¬P(x)", "∃x P(x)", "¬∃x P(x)"],
        note: "Flip the quantifier and negate the predicate.",
      },
      {
        id: "pq-neg-exists",
        q: "Push the negation in: ¬∃x P(x) ≡ ?",
        a: "∀x ¬P(x)",
        distractors: ["∃x ¬P(x)", "∀x P(x)", "¬∀x P(x)"],
        note: "Flip the quantifier and negate the predicate.",
      },
      {
        id: "pq-finite-forall",
        q: "Over the domain {a, b, c}, ∀x P(x) expands to…",
        a: "P(a) ∧ P(b) ∧ P(c)",
        distractors: ["P(a) ∨ P(b) ∨ P(c)", "P(a) → P(b) → P(c)", "P(a) ⊕ P(b) ⊕ P(c)"],
        note: "∀ over a finite domain is a big AND.",
      },
      {
        id: "pq-finite-exists",
        q: "Over the domain {a, b, c}, ∃x P(x) expands to…",
        a: "P(a) ∨ P(b) ∨ P(c)",
        distractors: ["P(a) ∧ P(b) ∧ P(c)", "P(a) → P(b) → P(c)", "¬P(a) ∧ ¬P(b) ∧ ¬P(c)"],
        note: "∃ over a finite domain is a big OR.",
      },
      {
        id: "pq-distribute",
        q: "Which distribution of a quantifier is VALID?",
        a: "∀x (P(x) ∧ Q(x)) ≡ ∀x P(x) ∧ ∀x Q(x)",
        distractors: ["∀x (P(x) ∨ Q(x)) ≡ ∀x P(x) ∨ ∀x Q(x)", "∃x (P(x) ∧ Q(x)) ≡ ∃x P(x) ∧ ∃x Q(x)", "∀x P(x) ∨ Q(x) ≡ P(x) ∧ ∀x Q(x)"],
        note: "∀ distributes over ∧, and ∃ over ∨ — but NOT ∀ over ∨, nor ∃ over ∧.",
      },
      {
        id: "pq-order-same",
        q: "Which reordering of quantifiers is always valid?",
        a: "∀x ∀y P(x, y) ≡ ∀y ∀x P(x, y)",
        distractors: ["∀x ∃y P(x, y) ≡ ∃y ∀x P(x, y)", "∃x ∀y P(x, y) ≡ ∀y ∃x P(x, y)", "∀x ∃y P(x, y) ≡ ∀y ∃x P(x, y)"],
        note: "Same-type quantifiers commute; mixed ones generally do not.",
      },
      {
        id: "pq-order-mixed",
        q: "Which implication between mixed quantifiers always holds?",
        a: "∃y ∀x P(x, y) ⇒ ∀x ∃y P(x, y)",
        distractors: ["∀x ∃y P(x, y) ⇒ ∃y ∀x P(x, y)", "∀x ∃y P(x, y) ⇔ ∃y ∀x P(x, y)", "Neither direction holds"],
        note: "If one y works for all x, then each x has some y (the same one). The converse fails.",
      },
      {
        id: "pq-forall-false-when",
        q: "∀x P(x) is FALSE exactly when…",
        a: "there is at least one x with ¬P(x) (a counterexample)",
        distractors: ["P(x) is false for every x", "P(x) is true for some x", "the domain is infinite"],
        note: "A single counterexample defeats a universal.",
      },
      {
        id: "pq-exists-false-when",
        q: "∃x P(x) is FALSE exactly when…",
        a: "P(x) fails for every x in the domain",
        distractors: ["P(x) fails for some x", "P(x) holds for exactly one x", "the domain is empty"],
        note: "No witness anywhere ⇒ the existential is false.",
      },
      {
        id: "pq-domain-dependence",
        q: "\"∀x, x ≥ 0\" — can its truth value change with the domain?",
        a: "Yes — true over ℕ, false over ℤ",
        distractors: [
          "No — it's true in every domain",
          "No — it's false in every domain",
          "Only if the domain is empty",
        ],
        note: "Truth of a quantified statement always depends on the chosen domain.",
      },
      {
        id: "pq-neg-nested",
        q: "Push the negation fully inward: ¬∀x ∃y P(x, y) ≡ ?",
        a: "∃x ∀y ¬P(x, y)",
        distractors: ["∀x ∃y ¬P(x, y)", "∃x ∃y ¬P(x, y)", "∀x ∀y ¬P(x, y)"],
        note: "Flip every quantifier as ¬ moves in (∀→∃, ∃→∀), then negate the predicate.",
      },
      {
        id: "pq-free-bound-2",
        q: "In ∃y (P(x) ∧ Q(y, z)), which variables are free?",
        a: "x and z",
        distractors: ["y only", "x, y, and z", "z only"],
        note: "Only y is bound (by ∃y); x and z are free, so the formula is still a predicate.",
      },
      {
        id: "pq-english-forall",
        q: "\"Every student passed\" (domain: students, Passed(x)) translates to…",
        a: "∀x Passed(x)",
        distractors: ["∃x Passed(x)", "¬∃x Passed(x)", "∃!x Passed(x)"],
        note: "\"Every / all\" is the universal quantifier.",
      },
      {
        id: "pq-english-neg",
        q: "\"No student failed\" (Failed(x)) is best written as…",
        a: "∀x ¬Failed(x)  (equivalently ¬∃x Failed(x))",
        distractors: ["∃x ¬Failed(x)", "¬∀x Failed(x)", "∃x Failed(x)"],
        note: "\"No x\" = ¬∃x = ∀x ¬ … by quantifier negation.",
      },
      {
        id: "pq-order-love",
        q: "\"Everyone loves someone\" (L(x,y) = x loves y) is…",
        a: "∀x ∃y L(x, y)",
        distractors: ["∃y ∀x L(x, y)", "∀x ∀y L(x, y)", "∃x ∃y L(x, y)"],
        note: "Pick x first, then find a y — the y may depend on x.",
      },
      {
        id: "pq-order-love-stronger",
        q: "Which statement is STRONGER (harder to satisfy)?",
        a: "∃y ∀x L(x, y) — someone is loved by everyone",
        distractors: [
          "∀x ∃y L(x, y) — everyone loves someone",
          "They are equivalent",
          "∀x ∃y is stronger",
        ],
        note: "One fixed y working for all x implies everyone-loves-someone, but not vice versa.",
      },
      {
        id: "pq-distribute-invalid",
        q: "Which quantifier distribution is INVALID?",
        a: "∀x (P(x) ∨ Q(x)) ≡ ∀x P(x) ∨ ∀x Q(x)",
        distractors: [
          "∀x (P(x) ∧ Q(x)) ≡ ∀x P(x) ∧ ∀x Q(x)",
          "∃x (P(x) ∨ Q(x)) ≡ ∃x P(x) ∨ ∃x Q(x)",
          "¬∀x P(x) ≡ ∃x ¬P(x)",
        ],
        note: "∀ does NOT distribute over ∨ (nor ∃ over ∧).",
      },
      {
        id: "pq-ground-recognize",
        q: "Which of these is a ground formula?",
        a: "Even(4) ∧ Prime(4)",
        distractors: ["∀x Even(x)", "Even(x) ∧ Prime(x)", "∃x Prime(x)"],
        note: "Ground = no variables left; every term is a concrete value.",
      },
      {
        id: "pq-predicate-vs-prop",
        q: "P(x) with x free is a predicate. What turns it into a proposition?",
        a: "Binding x with a quantifier or substituting a specific value",
        distractors: [
          "Choosing a larger domain",
          "Negating it",
          "Adding a second free variable",
        ],
        note: "A proposition has a definite truth value; a free variable prevents that.",
      },
      {
        id: "pq-exists-unique-expand",
        q: "∃!x P(x) can be unpacked as \"∃x P(x) and…\"",
        a: "for all y, P(y) implies y = x (uniqueness)",
        distractors: [
          "for all y, P(y) (everyone satisfies P)",
          "there is another z with P(z)",
          "¬∃x P(x)",
        ],
        note: "Existence plus uniqueness: any two things satisfying P must be equal.",
      },
    ],
  },

  {
    id: "prenex-normal-form",
    module: "m1",
    title: "Prenex Normal Form",
    cards: [
      {
        id: "pnf-what",
        q: "A formula is in prenex normal form when…",
        a: "all quantifiers are at the front and the body (matrix) is quantifier-free",
        distractors: ["it contains no quantifiers at all", "it is written as an OR of AND-clauses", "every quantifier is ∃"],
        note: "The quantifier-free body is called the matrix.",
      },
      {
        id: "pnf-step1",
        q: "What is Step 1 of converting to prenex normal form?",
        a: "Eliminate implications (rewrite → using ¬P ∨ Q)",
        distractors: ["Pull quantifiers to the front", "Rename variables to avoid capture", "Push negations inward"],
        note: "Leave only ∧, ∨, ¬ before you move quantifiers.",
      },
      {
        id: "pnf-step2",
        q: "What is Step 2 of converting to prenex normal form?",
        a: "Push negations inward (De Morgan for ∧/∨ and for quantifiers)",
        distractors: ["Eliminate implications", "Pull quantifiers to the front", "Distribute ∧ over ∨"],
        note: "Move each ¬ in until it applies only to a predicate.",
      },
      {
        id: "pnf-step3",
        q: "Why rename bound variables (Step 3) before pulling quantifiers out?",
        a: "To avoid variable capture when quantifiers move to the front",
        distractors: ["To eliminate implications", "To make the formula shorter", "To convert ∃ into ∀"],
        note: "Give bound variables fresh names so nothing collides.",
      },
      {
        id: "pnf-step4",
        q: "What is the final step (Step 4) of the prenex conversion?",
        a: "Pull the quantifiers outward to the front, leaving a quantifier-free matrix",
        distractors: ["Push negations inward", "Rename variables", "Eliminate biconditionals"],
        note: "Order is preserved as the quantifiers move out.",
      },
      {
        id: "pnf-matrix",
        q: "In a prenex formula, what is the \"matrix\"?",
        a: "The quantifier-free body after the leading quantifiers",
        distractors: ["The list of leading quantifiers", "The domain of the variables", "The negation of the formula"],
        note: "Prenex = quantifier prefix + quantifier-free matrix.",
      },
      {
        id: "pnf-first-step",
        q: "Which step comes FIRST when converting to prenex form?",
        a: "Eliminate implications and biconditionals",
        distractors: ["Pull quantifiers to the front", "Rename variables", "Push negations inward"],
        note: "Order: eliminate → , push ¬ in, rename, then pull quantifiers out.",
      },
      {
        id: "pnf-last-step",
        q: "Which step comes LAST when converting to prenex form?",
        a: "Pull the quantifiers to the front",
        distractors: ["Eliminate implications", "Push negations inward", "Rename bound variables"],
        note: "You can only pull quantifiers out safely after renaming to avoid capture.",
      },
      {
        id: "pnf-is-prenex",
        q: "Which formula IS already in prenex normal form?",
        a: "∀x ∃y (P(x) ∨ ¬Q(y))",
        distractors: [
          "∀x (P(x) → ∃y Q(y))",
          "(∀x P(x)) ∧ (∃y Q(y))",
          "¬∀x (P(x) ∧ Q(x))",
        ],
        note: "All quantifiers must sit at the very front, with a quantifier-free body.",
      },
      {
        id: "pnf-neg-in-step2",
        q: "During Step 2, ¬∀x P(x) becomes…",
        a: "∃x ¬P(x)",
        distractors: ["∀x ¬P(x)", "¬∃x P(x)", "∃x P(x)"],
        note: "De Morgan for quantifiers flips ∀ to ∃ as the negation moves inward.",
      },
      {
        id: "pnf-why-rename",
        q: "In ∀x P(x) ∧ ∃x Q(x), why rename the second x before pulling quantifiers out?",
        a: "The two x's are different variables; renaming avoids capturing one under the other's quantifier",
        distractors: [
          "To turn ∃ into ∀",
          "To shorten the formula",
          "Because ∧ isn't allowed in prenex form",
        ],
        note: "Rename to e.g. ∃z Q(z), then ∀x ∃z (P(x) ∧ Q(z)) is safe.",
      },
    ],
  },

  {
    id: "dnf-cnf",
    module: "m1",
    title: "DNF / CNF Conversion",
    cards: [
      {
        id: "dc-dnf-shape",
        q: "What is the shape of Disjunctive Normal Form (DNF)?",
        a: "An OR of AND-clauses",
        distractors: ["An AND of OR-clauses", "A single big implication", "A chain of biconditionals"],
        note: "DNF = OR of ANDs; CNF = AND of ORs.",
      },
      {
        id: "dc-cnf-shape",
        q: "What is the shape of Conjunctive Normal Form (CNF)?",
        a: "An AND of OR-clauses",
        distractors: ["An OR of AND-clauses", "A single big disjunction", "A chain of implications"],
        note: "CNF = AND of ORs; DNF = OR of ANDs.",
      },
      {
        id: "dc-step1",
        q: "What is Step 1 of the DNF/CNF algorithm?",
        a: "Eliminate every connective except ∧, ∨, ¬ (rewrite →, ↔, ⊕)",
        distractors: ["Distribute to reach the target form", "Push negations inward", "Eliminate double negations"],
        note: "Get down to just ∧, ∨, ¬ first.",
      },
      {
        id: "dc-step2",
        q: "What is Step 2 of the DNF/CNF algorithm?",
        a: "Push negations inward using De Morgan's laws",
        distractors: ["Eliminate implications", "Distribute over the clauses", "Rename variables"],
        note: "Every ¬ should end up on a single variable.",
      },
      {
        id: "dc-step4-dnf",
        q: "To reach DNF in the final step, you distribute…",
        a: "∧ over ∨",
        distractors: ["∨ over ∧", "→ over ∧", "¬ over ∨"],
        note: "DNF: distribute ∧ over ∨. CNF: distribute ∨ over ∧.",
      },
      {
        id: "dc-step4-cnf",
        q: "To reach CNF in the final step, you distribute…",
        a: "∨ over ∧",
        distractors: ["∧ over ∨", "↔ over ∨", "¬ over ∧"],
        note: "CNF: distribute ∨ over ∧. DNF: distribute ∧ over ∨.",
      },
      {
        id: "dc-recognize-dnf",
        q: "Which formula is in DNF (disjunctive normal form)?",
        a: "(P ∧ ¬Q) ∨ (¬P ∧ R)",
        distractors: ["(P ∨ ¬Q) ∧ (¬P ∨ R)", "P → (Q ∨ R)", "¬(P ∧ Q)"],
        note: "DNF is an OR of AND-clauses of literals.",
      },
      {
        id: "dc-recognize-cnf",
        q: "Which formula is in CNF (conjunctive normal form)?",
        a: "(P ∨ ¬Q) ∧ (¬P ∨ R)",
        distractors: ["(P ∧ ¬Q) ∨ (¬P ∧ R)", "P ↔ (Q ∧ R)", "¬(P ∨ Q)"],
        note: "CNF is an AND of OR-clauses of literals.",
      },
      {
        id: "dc-literal",
        q: "In DNF/CNF, what is a \"literal\"?",
        a: "A variable or its negation, e.g. P or ¬Q",
        distractors: ["Any clause in parentheses", "A whole normal-form formula", "An implication P → Q"],
        note: "Clauses are built from literals joined by ∧ (in DNF) or ∨ (in CNF).",
      },
      {
        id: "dc-step-order",
        q: "Which is the correct order of the DNF/CNF algorithm?",
        a: "Eliminate connectives → push ¬ inward → remove double negations → distribute",
        distractors: [
          "Distribute → eliminate connectives → push ¬ inward",
          "Push ¬ inward → distribute → eliminate connectives",
          "Eliminate connectives → distribute → push ¬ inward",
        ],
        note: "You can't distribute correctly until ¬ sits on single variables.",
      },
      {
        id: "dc-eliminate-iff",
        q: "Step 1 rewrites P ↔ Q as…",
        a: "(P → Q) ∧ (Q → P), then each → is eliminated",
        distractors: ["¬P ∨ Q", "(P ∧ Q) ∨ (¬P ∨ ¬Q)", "P ⊕ Q"],
        note: "Biconditionals expand to two implications, which then become ∨/¬.",
      },
      {
        id: "dc-demorgan-step2",
        q: "In Step 2, ¬(P ∨ Q) is rewritten as…",
        a: "¬P ∧ ¬Q",
        distractors: ["¬P ∨ ¬Q", "P ∧ Q", "¬(P ∧ Q)"],
        note: "De Morgan pushes the negation onto each variable, flipping ∨ to ∧.",
      },
      {
        id: "dc-distribute-dnf-apply",
        q: "Distributing P ∧ (Q ∨ R) toward DNF gives…",
        a: "(P ∧ Q) ∨ (P ∧ R)",
        distractors: ["(P ∨ Q) ∧ (P ∨ R)", "P ∨ (Q ∧ R)", "(P ∧ Q) ∧ R"],
        note: "DNF distributes ∧ over ∨ to produce an OR of AND-clauses.",
      },
    ],
  },
];
