// ============================================================================
// Study Notes — content (hand-authored)
// ----------------------------------------------------------------------------
// This file IS the cheat sheet. To add material, just append to NOTES below.
// There is no editor and nothing is persisted — edit this file directly.
//
// A section:
//   {
//     id: "kebab-id",              // unique, used for the TOC anchor
//     title: "Section Title",
//     blurb: "optional one-liner shown under the title",   // optional
//     cards: [ ...cards ],
//   }
//
// A card is ONE of these shapes (set `kind`):
//   • equivalence / rule:
//       { kind: "equiv", name: "Name", lhs: "LHS", rhs: "RHS", note: "..." }
//       → renders   Name:  LHS ≡ RHS   (note is optional, shown muted)
//     For a law with several forms, use `rows` instead of lhs/rhs:
//       { kind: "equiv", name: "Name", rows: [ {lhs,rhs}, {lhs,rhs} ], note }
//   • algorithm step:
//       { kind: "step", n: 1, title: "...", detail: "...",
//         examples: [ { from: "P → Q", to: "¬P ∨ Q" }, ... ] }
//   • prose:
//       { kind: "text", title: "optional", body: "paragraph text" }
//   • theorem statement (a named result that isn't an equivalence):
//       { kind: "thm", name: "Triangle inequality", statement: "|a + b| ≤ |a| + |b|", note: "..." }
//       → renders   Name  +  a formula-styled statement chip  (note optional, muted)
//   • inference rule:
//       { kind: "infer", name: "Modus ponens",
//         premises: ["A", "A → B"], conclusion: "B", note: "..." }
//       → renders   Name:  A , A → B  ⊢  B   (note is optional, shown muted)
//   • form → strategy map (two-column reference):
//       { kind: "map", name: "...", rows: [ { from: "∀x. P(x)", to: "Let x be arbitrary…" } ], note: "..." }
//       → renders each row as   formula → prose   (note is optional, shown muted)
//
// TEMPLATE — copy a block and fill it in:
//   {
//     id: "my-topic",
//     title: "My Topic",
//     cards: [
//       { kind: "equiv", name: "Some rule", lhs: "P ∧ Q", rhs: "Q ∧ P" },
//     ],
//   },
// ============================================================================

export const NOTES = [
  {
    id: "nt-intro",
    module: "m2",
    title: "Introduction to Number Theory",
    blurb: "What we study, and the definition that starts it all: divides.",
    cards: [
      { kind: "text", title: "What is number theory?",
        body: "The study of the integers ℤ = {…, −2, −1, 0, 1, 2, …} and their structure — divisibility, primes, factorization, and congruences. It's foundational in computer science: cryptography (RSA), hashing, error-correcting codes, and algorithm analysis all rest on it." },
      { kind: "text", title: "The integers are closed under + − ×",
        body: "Add, subtract, or multiply two integers and you get an integer. They are NOT closed under division: 3 / 2 is not an integer. Number theory is largely about when division does work out evenly — that's divisibility." },
      { kind: "thm", name: "Definition of divides",
        statement: "a | b  ⟺  b = a·k for some integer k  (a ≠ 0)",
        note: "Read \"a divides b.\" Then a is a divisor/factor of b, and b is a multiple of a. Example: 3 | 12 since 12 = 3·4; but 3 ∤ 7." },
      { kind: "text", title: "Vocabulary",
        body: "If a | b: a is a factor (or divisor) of b, and b is a multiple of a. \"a ∤ b\" means a does not divide b. Note every integer divides 0, and 1 divides every integer." },
    ],
  },
  {
    id: "tk-parity-divisibility",
    module: "m2",
    title: "Parity & Divisibility",
    blurb: "The workhorses of integer proofs.",
    cards: [
      { kind: "text", title: "Even / odd",
        body: "n is even iff n = 2k for some integer k; n is odd iff n = 2k + 1. Every integer is exactly one of the two." },
      { kind: "text", title: "Divides (a | b)",
        body: "a | b (\"a divides b\") means b = a·k for some integer k. Then a is a factor of b and b is a multiple of a." },
      { kind: "thm", name: "Parity of products", statement: "even × anything = even;  odd × odd = odd",
        note: "So n² is even iff n is even (and n² is odd iff n is odd)." },
      { kind: "thm", name: "Parity of sums", statement: "even ± even = even,  odd ± odd = even,  even ± odd = odd" },
      { kind: "thm", name: "Divisibility is transitive", statement: "a | b  and  b | c  ⟹  a | c" },
      { kind: "thm", name: "Divides a linear combination", statement: "a | b  and  a | c  ⟹  a | (bx + cy)  for all integers x, y",
        note: "The key fact behind many number-theory proofs." },
      { kind: "thm", name: "Divides a multiple", statement: "a | b  ⟹  a | bc  for every integer c" },
      { kind: "thm", name: "Size bound", statement: "a | b  and  b ≠ 0  ⟹  |a| ≤ |b|",
        note: "A nonzero multiple is at least as big as its divisor." },
    ],
  },
  {
    id: "nt-divisibility-template",
    module: "m2",
    title: "The Divisibility-Proof Template",
    blurb: "A reliable recipe for direct proofs about divisibility.",
    cards: [
      { kind: "text", title: "The idea",
        body: "Most direct proofs about divisibility follow the same five steps: set up your variables, unpack each divisibility hypothesis into an equation, do algebra, repackage the result using the definition of divides, and state the conclusion." },
      { kind: "step", n: 1, title: "Set up",
        detail: "Introduce your variables with their domains (\"Let a, b, c be integers…\") and state what you're assuming — the antecedent of the implication." },
      { kind: "step", n: 2, title: "Unpack the definitions",
        detail: "For each divisibility hypothesis like a | b, apply the definition to get an equation with a fresh integer: \"there exists m ∈ ℤ such that b = a·m.\"",
        examples: [ { from: "a | b", to: "b = a·m,  m ∈ ℤ" } ] },
      { kind: "step", n: 3, title: "Algebraic manipulation",
        detail: "Use substitution, factoring, and arithmetic to transform these equations toward the form you need for the conclusion. No fractions — everything is multiplication." },
      { kind: "step", n: 4, title: "Repackage using the definition",
        detail: "Identify the integer witness the definition requires, verify it's actually an integer (closure!), and write the divisibility statement.",
        examples: [ { from: "c = a·(m·n),  m·n ∈ ℤ", to: "a | c" } ] },
      { kind: "step", n: 5, title: "State the conclusion",
        detail: "Explicitly say what you've shown — e.g. \"Therefore a | c.\"" },
      { kind: "text", title: "Key reminders",
        body: "You should never need a fraction or division sign — divisibility works entirely through multiplication. Every new variable (like m, n) must be defined: where it comes from and its domain. And closure matters: when you form a quantity like m·n, say why it's an integer." },
    ],
  },
  {
    id: "tk-division-modular",
    module: "m2",
    title: "Division & Modular Arithmetic",
    blurb: "Quotients, remainders, and congruences.",
    cards: [
      { kind: "thm", name: "Division (Quotient–Remainder) Theorem",
        statement: "for a ∈ ℤ, d > 0 there are unique q, r with a = dq + r and 0 ≤ r < d",
        note: "q = ⌊a/d⌋ is the quotient, r = a mod d is the remainder." },
      { kind: "text", title: "Congruence mod m",
        body: "a ≡ b (mod m) means m | (a − b) — a and b leave the same remainder when divided by m." },
      { kind: "equiv", name: "Congruences add & multiply", rows: [
        { lhs: "a ≡ b, c ≡ d (mod m)", rhs: "a + c ≡ b + d (mod m)" },
        { lhs: "a ≡ b, c ≡ d (mod m)", rhs: "ac ≡ bd (mod m)" },
      ], note: "so also a^k ≡ b^k (mod m) for k ≥ 0" },
      { kind: "thm", name: "Modular inverse exists",
        statement: "a has an inverse mod m  ⟺  gcd(a, m) = 1",
        note: "then ax ≡ 1 (mod m) is solvable." },
      { kind: "thm", name: "Fermat's Little Theorem",
        statement: "p prime  ⟹  aᵖ ≡ a (mod p);  if p ∤ a then aᵖ⁻¹ ≡ 1 (mod p)",
        note: "A staple for simplifying powers modulo a prime." },
    ],
  },
  {
    id: "tk-congruence-classes",
    module: "m2",
    title: "Modular Arithmetic & Congruence Classes",
    blurb: "The biconditional proof tool, and why division can fail in ℤₙ.",
    cards: [
      { kind: "thm", name: "The Biconditional Theorem",
        statement: "a ≡ b (mod n)  ⟺  n | (a − b)",
        note: "Your primary tool for the rest of modular arithmetic — it turns congruence into divisibility." },
      { kind: "text", title: "Converting congruence to divisibility",
        body: "To prove a ≡ b (mod n), it's often easiest to show n | (a − b). Then use the divisibility toolkit — unpack definitions, substitute, repackage — to finish the congruence proof." },
      { kind: "text", title: "Two directions, two uses",
        body: "Forward (⇒): from a ≡ b (mod n) conclude n | (a − b), giving a divisibility fact to work with. Reverse (⇐): once you've shown n | (a − b), conclude a ≡ b (mod n)." },
      { kind: "text", title: "The proof, in two parts",
        body: "Reverse (⇐): given n | (a − b), a and b have the same remainder — the only multiple of n strictly between −n and n is 0. Forward (⇒): if a = nq₁ + r and b = nq₂ + r, then a − b = n(q₁ − q₂), so n | (a − b). The two directions together give the biconditional." },
      { kind: "text", title: "Biconditional proofs are a recurring pattern",
        body: "Proving ⇒ and ⇐ separately shows up throughout the course — again in set equality (A ⊆ B and B ⊆ A) and function bijectivity (injective and surjective)." },
      { kind: "text", title: "Quick example",
        body: "Is 47 ≡ 11 (mod 9)? Check 47 − 11 = 36 = 9·4. Since 9 | 36, yes — 47 ≡ 11 (mod 9). ✓" },
      { kind: "text", title: "Zero divisors",
        body: "In ℤ a product is zero only if a factor is zero. In ℤₙ this can fail: in ℤ₁₂, [3]·[4] = [12] = [0] though neither is [0]. Such nonzero elements whose product is 0 are called zero divisors." },
      { kind: "text", title: "Why cancellation can fail",
        body: "Over ℤ, ac = bc with c ≠ 0 lets you cancel c. In ℤₙ you can't cancel a zero divisor: [3]·[a] ≡ [3]·[b] (mod 12) does NOT give a ≡ b, because [3] is a zero divisor in ℤ₁₂. You can cancel exactly when the element is invertible." },
      { kind: "thm", name: "Invertible or zero divisor — no middle ground",
        statement: "in ℤₙ, [a] is invertible if gcd(a, n) = 1, otherwise a zero divisor (gcd(a, n) > 1)",
        note: "Every nonzero element is exactly one of the two. The inverse is the tool that replaces division." },
    ],
  },
  {
    id: "tk-gcd-euclid",
    module: "m2",
    title: "GCD & the Euclidean Algorithm",
    blurb: "Greatest common divisors and how to compute them.",
    cards: [
      { kind: "text", title: "Greatest common divisor",
        body: "gcd(a, b) is the largest integer that divides both a and b. By convention gcd(a, 0) = |a|. d is a common divisor of a and b when d | a and d | b — the gcd is the greatest such d." },
      { kind: "text", title: "Coprime",
        body: "a and b are coprime (relatively prime) iff gcd(a, b) = 1 — they share no common factor besides 1." },
      { kind: "thm", name: "Euclidean algorithm identity",
        statement: "gcd(a, b) = gcd(b, a mod b),  with  gcd(a, 0) = |a|",
        note: "The remainder shares all common divisors with the original pair." },
      { kind: "step", n: 1, title: "Divide",
        detail: "Write a = q·b + r with 0 ≤ r < b (the Division Algorithm).",
        examples: [ { from: "gcd(48, 18)", to: "48 = 2·18 + 12" } ] },
      { kind: "step", n: 2, title: "Replace and repeat",
        detail: "Replace (a, b) with (b, r) and divide again — keep going until the remainder is 0.",
        examples: [
          { from: "gcd(18, 12)", to: "18 = 1·12 + 6" },
          { from: "gcd(12, 6)", to: "12 = 2·6 + 0" },
        ] },
      { kind: "step", n: 3, title: "Read off the gcd",
        detail: "The last nonzero remainder is gcd(a, b).",
        examples: [ { from: "last nonzero remainder", to: "gcd(48, 18) = 6" } ] },
      { kind: "thm", name: "Bézout's Identity",
        statement: "gcd(a, b) = ax + by  for some integers x, y",
        note: "The gcd is the smallest positive integer of this form." },
      { kind: "text", title: "Extended Euclidean Algorithm",
        body: "Run the Euclidean algorithm, then back-substitute the equations to express gcd(a, b) as ax + by — this yields the Bézout coefficients x, y, and gives modular inverses (x is a⁻¹ mod b when gcd(a, b) = 1)." },
      { kind: "thm", name: "GCD–LCM relation",
        statement: "gcd(a, b) · lcm(a, b) = |a · b|",
        note: "lcm(a, b) is the least common multiple — the smallest positive multiple of both." },
    ],
  },
  {
    id: "tk-primes-gcd",
    module: "m2",
    title: "Primes & Factorization",
    blurb: "The building blocks of the integers.",
    cards: [
      { kind: "text", title: "Prime",
        body: "An integer p ≥ 2 is prime iff its only positive divisors are 1 and p." },
      { kind: "text", title: "Composite",
        body: "An integer n ≥ 2 is composite iff it is not prime — equivalently, n = ab for some integers with 1 < a, b < n. The number 1 is neither prime nor composite; this convention keeps unique factorization clean." },
      { kind: "infer", name: "Euclid's Lemma", premises: ["p prime", "p | ab"], conclusion: "p | a  or  p | b",
        note: "The property that makes primes \"prime\"." },
      { kind: "thm", name: "Fundamental Theorem of Arithmetic",
        statement: "every integer n ≥ 2 has a unique prime factorization (up to order)",
        note: "e.g. 12 = 2²·3, 2310 = 2·3·5·7·11, and 97 is prime (it factors only as itself)." },
      { kind: "thm", name: "Factorization ⇒ divisibility",
        statement: "a | b  iff every prime in a's factorization appears in b's with an exponent at least as large",
        note: "12 = 2²·3 divides 60 = 2²·3·5, but 12 ∤ 18 = 2·3² — 12 needs 2² while 18 has only 2¹." },
      { kind: "thm", name: "Infinitude of primes",
        statement: "there are infinitely many primes",
        note: "Euclid: given primes p₁…pₖ, the number p₁···pₖ + 1 has a prime factor not among them." },
    ],
  },
  {
    id: "st-sets-operations",
    module: "m2",
    title: "Sets & Set Operations",
    blurb: "Collections of elements, and the operations that combine them.",
    cards: [
      { kind: "text", title: "Set, element, subset",
        body: "A set is an unordered collection of distinct elements. x ∈ A means x is in A; x ∉ A means it isn't. A ⊆ B (A is a subset of B) means every element of A is in B. A = B iff A ⊆ B and B ⊆ A." },
      { kind: "text", title: "Special sets",
        body: "The empty set ∅ = {} has no elements. Set-builder notation { x : P(x) } collects every x satisfying P. The power set P(A) is the set of all subsets of A." },
      { kind: "thm", name: "Union", statement: "A ∪ B = { x : x ∈ A or x ∈ B }" },
      { kind: "thm", name: "Intersection", statement: "A ∩ B = { x : x ∈ A and x ∈ B }" },
      { kind: "thm", name: "Complement", statement: "Ā = { x : x ∉ A }",
        note: "relative to a universal set U" },
      { kind: "thm", name: "Difference", statement: "A ∖ B = { x : x ∈ A and x ∉ B }" },
    ],
  },
  {
    id: "st-sets-logic",
    module: "m2",
    title: "The Sets–Logic Correspondence & Set Proofs",
    blurb: "Every logical identity has a set-theory counterpart — and how to prove A = B.",
    cards: [
      { kind: "map", name: "Set operation ↔ logic connective", rows: [
        { from: "A ∪ B", to: "P ∨ Q — x ∈ A or x ∈ B" },
        { from: "A ∩ B", to: "P ∧ Q — x ∈ A and x ∈ B" },
        { from: "Ā", to: "¬P — x ∉ A" },
        { from: "A ∖ B", to: "P ∧ ¬Q — x ∈ A and x ∉ B" },
      ], note: "membership in a compound set is a logical statement about x" },
      { kind: "text", title: "Every logical identity has a set counterpart",
        body: "Translate a propositional identity through the correspondence to get a set identity. De Morgan ¬(P ∨ Q) ≡ ¬P ∧ ¬Q becomes (A ∪ B)‾ = Ā ∩ B̄. Distributive P ∨ (Q ∧ R) ≡ (P ∨ Q) ∧ (P ∨ R) becomes A ∪ (B ∩ C) = (A ∪ B) ∩ (A ∪ C)." },
      { kind: "text", title: "Method 1 — Mutual containment",
        body: "Prove A ⊆ B and B ⊆ A separately. To show A ⊆ B: let x be an arbitrary element of A, then show x ∈ B. Each direction is a direct proof with hypothesis \"x ∈ A\" and conclusion \"x ∈ B.\"" },
      { kind: "text", title: "Method 2 — If-and-only-if chain",
        body: "Start with \"x ∈ (left side),\" expand using the set-operation definitions into logic, apply logical equivalences, then repackage into \"x ∈ (right side).\" Every step must be an \"iff\" (↔), not just an implication." },
      { kind: "text", title: "The core idea",
        body: "Both methods reason about an arbitrary element — the set-theory version of the same strategy from the divisibility segment: unpack definitions, manipulate, repackage." },
    ],
  },
  {
    id: "st-cardinality",
    module: "m2",
    title: "Cardinality, Inclusion–Exclusion & the Product Rule",
    blurb: "Counting the elements of finite sets.",
    cards: [
      { kind: "text", title: "Cardinality",
        body: "|A| is the number of elements in a finite set A. Watch the nesting: |{2, 4, 6}| = 3, but |{{2, 4, 6}}| = 1 (one element, which is a set) and |{ℕ}| = 1. The empty set has |∅| = 0." },
      { kind: "thm", name: "Inclusion–Exclusion (two sets)",
        statement: "|A ∪ B| = |A| + |B| − |A ∩ B|",
        note: "adding |A| and |B| double-counts A ∩ B, so subtract it once." },
      { kind: "thm", name: "Product Rule",
        statement: "|A × B| = |A| · |B|",
        note: "each ordered pair picks one element from A and one from B." },
      { kind: "thm", name: "Power Set Size",
        statement: "|P(A)| = 2^|A|",
        note: "each element is either in or out of a subset — |A| independent binary choices." },
      { kind: "text", title: "Quick check",
        body: "If |A| = 5, |B| = 6, and |A ∩ B| = 2, then |A ∪ B| = 5 + 6 − 2 = 9, |A × B| = 30, and |P(A)| = 32." },
    ],
  },
  {
    id: "rf-relations-functions",
    module: "m2",
    title: "Binary Relations & Functions",
    blurb: "Mappings between sets, made precise.",
    cards: [
      { kind: "thm", name: "Binary relation",
        statement: "a relation from A to B is a subset R ⊆ A × B (a set of ordered pairs)",
        note: "\"every integer n has a square n²\" is a relation from ℤ to ℤ; \"every student lives in a House\" relates students to Houses." },
      { kind: "text", title: "Function",
        body: "A function f : A → B is a relation that assigns to every element of A exactly one element of B. A is the domain, B the codomain. Functions are a special case of relations with that extra \"exactly one output\" constraint." },
      { kind: "text", title: "Bubble (arrow) diagrams",
        body: "Draw the domain on the left, the codomain on the right, and arrows for related pairs. You can read properties like injectivity and surjectivity off the diagram at a glance." },
    ],
  },
  {
    id: "rf-function-properties",
    module: "m2",
    title: "Proving Function Properties",
    blurb: "Injective, surjective, bijective — and how to prove each.",
    cards: [
      { kind: "text", title: "The three properties",
        body: "f is injective (one-to-one) if different inputs give different outputs; surjective (onto) if every codomain element is hit; bijective if both. Proving them follows the same \"unpack the definition\" pattern as the rest of the course." },
      { kind: "step", n: 1, title: "Prove f is injective",
        detail: "Assume f(x₁) = f(x₂) for arbitrary x₁, x₂ in the domain, then show x₁ = x₂. It's a direct proof of the conditional f(x₁) = f(x₂) → x₁ = x₂." },
      { kind: "step", n: 2, title: "Prove f is surjective",
        detail: "Let y be an arbitrary element of the codomain and exhibit an x in the domain with f(x) = y — usually solve f(x) = y for x, then check x is actually in the domain." },
      { kind: "step", n: 3, title: "Prove f is bijective",
        detail: "Prove injective and surjective separately, as two sub-proofs." },
      { kind: "text", title: "The parallel with subset proofs",
        body: "Same \"pick an arbitrary element\" pattern as the sets segment: to prove A ⊆ B pick an arbitrary element of A and show it's in B; to prove surjectivity pick an arbitrary codomain element and show it has a preimage." },
    ],
  },
  {
    id: "rf-composition",
    module: "m2",
    title: "Function Composition",
    blurb: "Chaining functions — and reading the notation correctly.",
    cards: [
      { kind: "thm", name: "Composition",
        statement: "for f : A → B and g : B → C,  (g ∘ f)(x) = g(f(x)),  g ∘ f : A → C",
        note: "You can compose when the codomain of f matches the domain of g." },
      { kind: "text", title: "Read the notation carefully",
        body: "g ∘ f means \"first apply f, then apply g\" — the notation order is the reverse of the order of application. This is a common source of errors." },
      { kind: "thm", name: "Composition preserves structure",
        statement: "g ∘ f is injective if f, g are injective;  surjective if f, g are surjective",
        note: "The general inheritance question is subtler than it first appears — bubble diagrams help explore it." },
    ],
  },
  {
    id: "rf-proof-review",
    module: "m2",
    title: "Proof Review as a Learning Tool",
    blurb: "Critically reading proofs sharpens your own.",
    cards: [
      { kind: "text", title: "Why review others' proofs",
        body: "Critically reading other people's proofs activates a different kind of attention than writing your own — you catch logic errors, gaps in justification, and stylistic issues you'd gloss over in your own work." },
      { kind: "map", name: "What to check as you read", rows: [
        { from: "Each step", to: "does it follow logically from what came before?" },
        { from: "Quantifiers", to: "are ∀ vs. ∃ used correctly, and in the right order?" },
        { from: "Notation", to: "is it consistent — are A and B the right sets?" },
        { from: "Precision", to: "is the argument precise, or does it rely on hand-waving?" },
      ] },
    ],
  },
  {
    id: "m3-proof-by-contradiction",
    module: "m3",
    title: "Proof by Contradiction",
    blurb: "Assume the opposite, derive an impossibility.",
    cards: [
      { kind: "text", title: "The idea",
        body: "To prove a statement P, assume its negation ¬P and derive a contradiction — something that cannot be true (like 0 = 1, or an integer that is both even and odd). Since ¬P leads to an impossibility, ¬P must be false, so P is true. Also called reductio ad absurdum." },
      { kind: "thm", name: "Logical basis",
        statement: "(¬P → (Q ∧ ¬Q))  ⟹  P",
        note: "If assuming ¬P forces a contradiction Q ∧ ¬Q, then P holds." },
      { kind: "step", n: 1, title: "Assume the negation",
        detail: "Suppose, for contradiction, that the statement is false — write down ¬P explicitly. For \"P → Q\" the negation to assume is P ∧ ¬Q." },
      { kind: "step", n: 2, title: "Reason toward an impossibility",
        detail: "Work forward with your definitions and known facts until two claims collide — a statement and its own negation, or a plainly false equation." },
      { kind: "step", n: 3, title: "Conclude",
        detail: "The contradiction shows the assumption ¬P is untenable, so P is true. End with \"— a contradiction. Therefore P.\"" },
      { kind: "text", title: "Classic example — √2 is irrational",
        body: "Assume √2 = a/b in lowest terms. Then a² = 2b², so a is even, say a = 2k; then 4k² = 2b², so b² = 2k² and b is even too. But then a and b share a factor of 2 — contradicting \"lowest terms.\" Hence √2 is irrational." },
      { kind: "text", title: "Classic example — infinitely many primes",
        body: "Assume there are finitely many primes p₁,…,pₖ. Consider N = p₁···pₖ + 1. N leaves remainder 1 when divided by each pᵢ, so no pᵢ divides N — yet N has a prime factor. That factor is a prime not in the list, a contradiction." },
      { kind: "text", title: "Contradiction vs. contrapositive",
        body: "To prove P → Q, contrapositive assumes ¬Q and derives ¬P (a direct proof of ¬Q → ¬P). Contradiction assumes P ∧ ¬Q and derives any contradiction. Contrapositive is often cleaner when the contradiction you'd reach is just ¬P." },
      { kind: "text", title: "When to reach for it",
        body: "Contradiction shines for non-existence and \"no such thing\" claims (irrationality, no largest prime, unsolvability) — assuming the thing exists gives you a concrete object to manipulate until it breaks." },
    ],
  },
  {
    id: "m3-pigeonhole",
    module: "m3",
    title: "The Pigeonhole Principle",
    blurb: "More objects than boxes forces a repeat.",
    cards: [
      { kind: "thm", name: "Pigeonhole Principle",
        statement: "if n objects are placed into k boxes and n > k, some box holds ≥ 2 objects",
        note: "\"More pigeons than holes\" ⟹ some hole has two pigeons. Purely existential — it says a repeat exists, not which box." },
      { kind: "thm", name: "Generalized Pigeonhole",
        statement: "n objects in k boxes  ⟹  some box holds ≥ ⌈n / k⌉ objects",
        note: "e.g. 100 people, 12 birth months ⟹ some month has ≥ ⌈100/12⌉ = 9 people." },
      { kind: "thm", name: "Contrapositive form",
        statement: "if every box holds ≤ m objects, then n ≤ k·m",
        note: "The way you often prove pigeonhole facts: bound each box, sum the bound." },
      { kind: "step", n: 1, title: "Identify the pigeons and the holes",
        detail: "Decide what the objects are and what the boxes/categories are. The whole art is choosing these so that n > k (or n > k·m)." },
      { kind: "step", n: 2, title: "Count",
        detail: "Show there are more objects than boxes (or more than k·(m−1) for the ⌈n/k⌉ form)." },
      { kind: "step", n: 3, title: "Conclude a collision",
        detail: "By pigeonhole, some box has two objects (or ≥ ⌈n/k⌉). Translate that collision back into the statement you wanted." },
      { kind: "text", title: "Classic example — same number of friends",
        body: "In any group of n ≥ 2 people, two people have the same number of friends within the group. Each person's friend count is in {0, …, n−1}, but 0 and n−1 can't both occur (someone with 0 friends and someone friends-with-everyone are incompatible), so only n−1 possible values remain for n people — a repeat is forced." },
      { kind: "text", title: "Classic example — five points in a square",
        body: "Among any 5 points in a unit square, two are within distance √2⁄2. Split the square into four ¼-squares (the boxes); 5 points in 4 boxes forces two points in one ¼-square, whose diagonal is √2⁄2." },
      { kind: "text", title: "Why it works",
        body: "It's just the contrapositive of counting: if no box had two objects, each box holds ≤ 1, so there'd be ≤ k objects total — contradicting n > k. The power is entirely in a clever choice of boxes." },
    ],
  },
  {
    id: "tk-rational-irrational",
    module: "toolkit",
    title: "Rational & Irrational Numbers",
    blurb: "Closure facts and the classic irrationality proof.",
    cards: [
      { kind: "text", title: "Rational",
        body: "x is rational iff x = p/q for integers p, q with q ≠ 0. Irrational means real but not rational." },
      { kind: "thm", name: "Rationals are closed",
        statement: "sum, difference, product, and quotient (÷ nonzero) of rationals are rational" },
      { kind: "thm", name: "Rational + irrational",
        statement: "rational + irrational = irrational",
        note: "Proof by contradiction: if the sum were rational, the irrational would be a difference of rationals." },
      { kind: "thm", name: "Nonzero rational × irrational",
        statement: "(nonzero rational) × irrational = irrational" },
      { kind: "thm", name: "√2 is irrational",
        statement: "√2 ∉ ℚ",
        note: "Assume √2 = p/q in lowest terms; then p² = 2q², so p is even, then q is even — contradicting lowest terms." },
      { kind: "thm", name: "Density of the rationals",
        statement: "between any two reals a < b there is a rational q with a < q < b" },
    ],
  },
  {
    id: "tk-summations",
    module: "toolkit",
    title: "Summation Formulas",
    blurb: "Closed forms you'll reach for (often proved by induction).",
    cards: [
      { kind: "equiv", name: "First n integers", lhs: "1 + 2 + … + n", rhs: "n(n + 1) / 2" },
      { kind: "equiv", name: "First n odd numbers", lhs: "1 + 3 + 5 + … + (2n − 1)", rhs: "n²" },
      { kind: "equiv", name: "Sum of squares", lhs: "1² + 2² + … + n²", rhs: "n(n + 1)(2n + 1) / 6" },
      { kind: "equiv", name: "Sum of cubes", lhs: "1³ + 2³ + … + n³", rhs: "(n(n + 1) / 2)²",
        note: "the square of the first-n-integers sum" },
      { kind: "equiv", name: "Geometric series", lhs: "1 + r + r² + … + rⁿ", rhs: "(rⁿ⁺¹ − 1) / (r − 1)",
        note: "for r ≠ 1" },
      { kind: "equiv", name: "Arithmetic series", lhs: "a + (a+d) + … + (a+(n−1)d)", rhs: "n(2a + (n − 1)d) / 2",
        note: "n terms · average of first and last" },
    ],
  },
  {
    id: "tk-inequalities",
    module: "toolkit",
    title: "Inequalities & Order",
    blurb: "Bounds that show up everywhere.",
    cards: [
      { kind: "thm", name: "Triangle inequality", statement: "|a + b| ≤ |a| + |b|" },
      { kind: "thm", name: "Reverse triangle inequality", statement: "| |a| − |b| | ≤ |a − b|" },
      { kind: "thm", name: "Transitivity of ≤", statement: "a ≤ b  and  b ≤ c  ⟹  a ≤ c" },
      { kind: "thm", name: "AM–GM (two variables)", statement: "(a + b) / 2 ≥ √(ab)  for a, b ≥ 0",
        note: "equality iff a = b" },
      { kind: "thm", name: "Bernoulli's inequality", statement: "(1 + x)ⁿ ≥ 1 + nx  for x ≥ −1, n ∈ ℕ" },
    ],
  },
  {
    id: "tk-floor-ceiling",
    module: "toolkit",
    title: "Floor & Ceiling",
    blurb: "Rounding functions and their identities.",
    cards: [
      { kind: "text", title: "Definitions",
        body: "⌊x⌋ is the greatest integer ≤ x; ⌈x⌉ is the least integer ≥ x." },
      { kind: "equiv", name: "Floor characterization", lhs: "⌊x⌋ = n", rhs: "n ≤ x < n + 1  (n ∈ ℤ)" },
      { kind: "equiv", name: "Ceiling characterization", lhs: "⌈x⌉ = n", rhs: "n − 1 < x ≤ n  (n ∈ ℤ)" },
      { kind: "equiv", name: "Ceiling from floor", lhs: "⌈x⌉", rhs: "−⌊−x⌋" },
      { kind: "thm", name: "Counting multiples", statement: "#{ k : 1 ≤ k ≤ n and m | k } = ⌊n / m⌋" },
      { kind: "equiv", name: "Integer split", rows: [
        { lhs: "⌊x⌋ + ⌈x⌉", rhs: "2x, if x ∈ ℤ" },
        { lhs: "⌊x⌋ + ⌈x⌉", rhs: "2⌊x⌋ + 1, if x ∉ ℤ" },
      ] },
    ],
  },
  {
    id: "tk-principles",
    module: "toolkit",
    title: "Foundational Principles",
    blurb: "The axioms behind induction and counting arguments.",
    cards: [
      { kind: "thm", name: "Well-Ordering Principle",
        statement: "every nonempty subset of ℕ has a least element",
        note: "The engine behind induction and many \"smallest counterexample\" proofs." },
      { kind: "thm", name: "Principle of Induction",
        statement: "P(0) and (∀k. P(k) → P(k+1))  ⟹  ∀n. P(n)" },
      { kind: "thm", name: "Strong Induction",
        statement: "P(0) and (∀k. (P(0)∧…∧P(k)) → P(k+1))  ⟹  ∀n. P(n)" },
      { kind: "thm", name: "Pigeonhole Principle",
        statement: "n items in k boxes with n > k  ⟹  some box holds ≥ 2 items" },
      { kind: "thm", name: "Generalized Pigeonhole",
        statement: "n items in k boxes  ⟹  some box holds ≥ ⌈n / k⌉ items" },
    ],
  },
  {
    id: "tk-counting-binomial",
    module: "toolkit",
    title: "Counting, Functions & the Binomial Theorem",
    blurb: "Combinatorial identities and map properties.",
    cards: [
      { kind: "thm", name: "Product & sum rules",
        statement: "|A × B| = |A|·|B|;  disjoint A, B: |A ∪ B| = |A| + |B|" },
      { kind: "thm", name: "Inclusion–Exclusion (two sets)",
        statement: "|A ∪ B| = |A| + |B| − |A ∩ B|" },
      { kind: "text", title: "Injective / surjective / bijective",
        body: "f is injective (one-to-one) if f(x)=f(y) ⟹ x=y; surjective (onto) if every codomain element is hit; bijective if both." },
      { kind: "thm", name: "Composition preserves structure",
        statement: "g∘f is injective if f, g are;  g∘f is surjective if f, g are" },
      { kind: "thm", name: "Binomial Theorem",
        statement: "(x + y)ⁿ = Σₖ₌₀ⁿ C(n, k) xᵏ yⁿ⁻ᵏ" },
      { kind: "thm", name: "Pascal's Rule",
        statement: "C(n, k) = C(n − 1, k − 1) + C(n − 1, k)" },
      { kind: "thm", name: "Sum of a row",
        statement: "Σₖ₌₀ⁿ C(n, k) = 2ⁿ",
        note: "the number of subsets of an n-element set" },
    ],
  },
  {
    id: "logical-forms",
    module: "m1",
    title: "Logical Forms",
    blurb: "Starting from an implication P → Q.",
    cards: [
      { kind: "equiv", name: "Converse", lhs: "P → Q", rhs: "Q → P", note: "swap the two sides" },
      { kind: "equiv", name: "Inverse", lhs: "P → Q", rhs: "¬P → ¬Q", note: "negate both sides" },
      { kind: "equiv", name: "Contrapositive", lhs: "P → Q", rhs: "¬Q → ¬P", note: "swap and negate — equivalent to the original" },
    ],
  },
  {
    id: "equivalence-laws",
    module: "m1",
    title: "Equivalence Laws",
    blurb: "The core rewriting rules. Many come in an ∧ form and an ∨ form.",
    cards: [
      { kind: "equiv", name: "Commutative", rows: [
        { lhs: "P ∧ Q", rhs: "Q ∧ P" },
        { lhs: "P ∨ Q", rhs: "Q ∨ P" },
      ], note: "order doesn't matter" },
      { kind: "equiv", name: "Associative", rows: [
        { lhs: "(P ∧ Q) ∧ R", rhs: "P ∧ (Q ∧ R)" },
        { lhs: "(P ∨ Q) ∨ R", rhs: "P ∨ (Q ∨ R)" },
      ], note: "grouping doesn't matter" },
      { kind: "equiv", name: "Distributive", rows: [
        { lhs: "P ∧ (Q ∨ R)", rhs: "(P ∧ Q) ∨ (P ∧ R)" },
        { lhs: "P ∨ (Q ∧ R)", rhs: "(P ∨ Q) ∧ (P ∨ R)" },
      ] },
      { kind: "equiv", name: "De Morgan", rows: [
        { lhs: "¬(P ∧ Q)", rhs: "¬P ∨ ¬Q" },
        { lhs: "¬(P ∨ Q)", rhs: "¬P ∧ ¬Q" },
      ], note: "a negation flips ∧ ↔ ∨" },
      { kind: "equiv", name: "Double negation", lhs: "¬(¬P)", rhs: "P" },
      { kind: "equiv", name: "Implication", lhs: "P → Q", rhs: "¬P ∨ Q" },
      { kind: "equiv", name: "Biconditional", lhs: "P ↔ Q", rhs: "(P → Q) ∧ (Q → P)" },
      { kind: "equiv", name: "Exclusive or (XOR)", lhs: "P ⊕ Q", rhs: "(P ∧ ¬Q) ∨ (¬P ∧ Q)", note: "also (P ∨ Q) ∧ ¬(P ∧ Q)" },
    ],
  },
  {
    id: "inference-rules",
    module: "m1",
    title: "Inference Rules",
    blurb: "Valid moves for reasoning forward: from the premises, conclude the result (⊢).",
    cards: [
      { kind: "infer", name: "Modus ponens", premises: ["A", "A → B"], conclusion: "B",
        note: "Forward reasoning: it's raining, and rain implies wet ground, so the ground is wet." },
      { kind: "infer", name: "Modus tollens", premises: ["¬B", "A → B"], conclusion: "¬A",
        note: "Modus ponens on the contrapositive: A → B ≡ ¬B → ¬A, then ¬B gives ¬A." },
      { kind: "infer", name: "And-elimination", premises: ["A ∧ B"], conclusion: "A",
        note: "If both are true you can conclude either one alone — likewise A ∧ B ⊢ B." },
    ],
  },
  {
    id: "direct-proofs",
    module: "m1",
    title: "Direct Proofs",
    blurb: "Reason straight from the givens to the conclusion — the workhorse strategy, driven by modus ponens and modus tollens.",
    tileLabel: "Checklist + strategies",
    cards: [
      { kind: "text", title: "The idea",
        body: "A direct proof reasons forward from what you're given to what you want, one justified step at a time. The engine is modus ponens (from A and A → B, conclude B) and modus tollens (from ¬B and A → B, conclude ¬A) — see the Inference Rules notes." },
      { kind: "text", title: "Direct proof checklist",
        body: "Work these on scratch paper before writing a single line of proof:" },
      { kind: "step", n: 1, title: "Identify givens",
        detail: "What facts are you given? What can you assume? Write them down." },
      { kind: "step", n: 2, title: "Gather definitions",
        detail: "If the claim mentions \"rational,\" \"even,\" \"prime,\" \"divides,\" etc., write down the formal definition. Definitions give you variables to work with and structure to exploit." },
      { kind: "step", n: 3, title: "Determine the logical structure",
        detail: "Express the claim as a predicate-logic formula (or at least recognize its form). Is it a universal? An implication? An existential? A combination? Note how each variable is quantified and over what domain (ℤ, ℝ, ℚ, ℕ, …)." },
      { kind: "step", n: 4, title: "Identify what you need to show",
        detail: "What does the conclusion look like formally? This is your finish line — knowing where you must end up guides your reasoning." },
      { kind: "step", n: 5, title: "Explore with examples",
        detail: "Plug in specific values. Try to break the claim. Understand why it's true — or discover that it's false." },
      { kind: "step", n: 6, title: "Select a proof strategy",
        detail: "Choose based on the logical structure (see the chart below). Strategies are often combined for claims that mix several logical forms." },
      { kind: "step", n: 7, title: "Write the proof",
        detail: "State the claim, introduce variables, reason step by step, and conclude explicitly." },
      { kind: "map", name: "Choosing a strategy by logical form", rows: [
        { from: "∀x. P(x)", to: "Let x be an arbitrary element of the domain. Show P(x)." },
        { from: "P → Q", to: "Assume P. Deduce Q." },
        { from: "∃x. P(x)", to: "Exhibit a specific x. Verify P(x)." },
        { from: "¬∀x. P(x)", to: "Find a counterexample: a specific x where P(x) fails." },
        { from: "¬∃x. P(x)", to: "Prove ∀x. ¬P(x) using the universal strategy." },
      ], note: "These combine: a claim like ∀x. (P(x) → Q(x)) uses the universal strategy, then the implication strategy inside." },
    ],
  },
  {
    id: "proof-by-cases",
    module: "m1",
    title: "Proof by Cases",
    blurb: "Split the domain into exhaustive cases, prove the claim in each, then conclude.",
    cards: [
      { kind: "text", title: "The principle",
        body: "To prove a claim about all elements of a domain, divide the domain into exhaustive cases, prove the claim separately in each case, and conclude that it holds in general. Every element must fall into at least one case." },
      { kind: "equiv", name: "Logical structure",
        lhs: "(C₁ ∨ C₂ ∨ … ∨ Cₖ) ∧ (C₁ → Q) ∧ … ∧ (Cₖ → Q)", rhs: "Q",
        note: "the cases are exhaustive (their disjunction always holds), and Q follows from each case" },
      { kind: "step", n: 1, title: "Identify a natural split",
        detail: "Find a natural way to divide the domain into cases (e.g. even vs. odd)." },
      { kind: "step", n: 2, title: "State the cases and argue they are exhaustive",
        detail: "List the cases explicitly and show every element falls into at least one — nothing is left out." },
      { kind: "step", n: 3, title: "Prove the claim in each case",
        detail: "Prove the claim separately within each case, using whatever that case gives you." },
      { kind: "step", n: 4, title: "Write a concluding sentence",
        detail: "\"Since the cases are exhaustive and the claim holds in each case, the claim is proved.\" Don't stop after the last case." },
      { kind: "map", name: "Common case divisions", rows: [
        { from: "Even vs. odd", to: "for integers" },
        { from: "Positive, negative, zero", to: "for integers or reals" },
        { from: "n mod 3 = 0, 1, 2", to: "for divisibility by 3" },
        { from: "n, n+1, n+2", to: "consecutive integers (when a product of consecutive integers appears)" },
      ] },
      { kind: "text", title: "When it's useful",
        body: "When the antecedent is a disjunction (\"if A or B, then Q\" — prove Q from A, then from B); when a property behaves differently for sub-types (even vs. odd); or when a single all-at-once argument gets stuck but each case has a simpler one." },
      { kind: "text", title: "Don't forget",
        body: "Verify the cases are exhaustive — proving it for some cases isn't enough. And write a concluding sentence that ties the cases together, so the reader sees you've covered everything." },
    ],
  },
  {
    id: "proving-uniqueness",
    module: "m1",
    title: "Proving Uniqueness",
    blurb: "Show something exists AND that it's the only one: ∃!y. P(y).",
    cards: [
      { kind: "text", title: "What ∃!y. P(y) means",
        body: "\"There exists a unique y such that P(y)\" asserts two things: Existence — there is at least one y satisfying P(y); and Uniqueness — there is at most one, so no two different values both work." },
      { kind: "step", n: 1, title: "Prove existence",
        detail: "Exhibit a specific value of y and verify P(y) — a standard existential proof (produce a witness)." },
      { kind: "step", n: 2, title: "Prove uniqueness",
        detail: "Assume two values y₀ and y₁ both satisfy P, then show y₀ = y₁. If two things satisfy the property, they must actually be the same — so there's really only one." },
      { kind: "text", title: "Worked example",
        body: "Claim: there is a unique integer k with k + 3 = 7. Existence: let k = 4; then 4 + 3 = 7 ✓. Uniqueness: suppose k₀ + 3 = 7 and k₁ + 3 = 7; then k₀ = 7 − 3 = 4 and k₁ = 7 − 3 = 4, so k₀ = k₁. Therefore k is unique. The method is always the same — real proofs just involve more algebra." },
    ],
  },
  {
    id: "predicates-quantifiers",
    module: "m1",
    title: "Predicates & Quantifiers",
    blurb: "Statements about objects in a domain, and the ∀ / ∃ that range over them.",
    cards: [
      { kind: "text", title: "Predicate",
        body: "A function from one or more domain values to a truth value, written P(x), Q(x, y), etc. On its own it isn't true or false — it becomes a proposition once its variables get specific values (e.g. Even(4)) or are bound by a quantifier. Examples: Even(x) means \"x is even\"; Loves(x, y) means \"x loves y.\" A predicate with 0 inputs is just a proposition — what we worked with in propositional logic." },
      { kind: "text", title: "Domain (universe of discourse)",
        body: "The set of objects the variables range over. It must be specified — the same formula can be true over one domain and false over another. Common domains: ℤ (integers), ℕ (natural numbers), ℝ (reals), or a described set like \"all students in the class.\"" },
      { kind: "text", title: "Universal quantifier — ∀",
        body: "∀x P(x) reads \"for all x in the domain, P(x) is true\" (write ∀x∈D. P(x) to name the domain). Think of it as an infinite AND: P(a₁) ∧ P(a₂) ∧ P(a₃) ∧ … over every element. A single counterexample makes it false." },
      { kind: "text", title: "Existential quantifier — ∃",
        body: "∃x P(x) reads \"there exists at least one x in the domain such that P(x) is true.\" Think of it as an infinite OR: P(a₁) ∨ P(a₂) ∨ P(a₃) ∨ … over every element. A single witness makes it true." },
      { kind: "text", title: "Uniqueness — ∃!",
        body: "∃!x P(x) reads \"there exists exactly one x such that P(x)\" — at least one, and no more than one." },
      { kind: "text", title: "Free vs bound variables",
        body: "A variable inside a quantifier's scope is bound — it has no individual identity, just a role. A variable not bound by any quantifier is free. A formula with free variables is still a predicate (not a proposition) — its truth depends on the values the free variables take. A formula with every variable bound is a proposition with a definite truth value. E.g. in ∀x P(x, y), x is bound and y is free." },
      { kind: "text", title: "Ground formula",
        body: "A formula with all variables replaced by specific domain values — it always evaluates to true or false. Example: Even(4) ∧ Prime(4) is a ground formula (and it's false)." },
      { kind: "equiv", name: "Quantifier negation (De Morgan for quantifiers)", rows: [
        { lhs: "¬∀x P(x)", rhs: "∃x ¬P(x)" },
        { lhs: "¬∃x P(x)", rhs: "∀x ¬P(x)" },
      ], note: "to push ¬ inward, flip the quantifier and negate the predicate" },
      { kind: "equiv", name: "Negating nested quantifiers",
        lhs: "¬∀x ∃y P(x, y)", rhs: "∃x ∀y ¬P(x, y)",
        note: "flip every quantifier (∀ ↔ ∃) as the ¬ moves in, then negate the innermost predicate" },
      { kind: "equiv", name: "Finite-domain expansion", rows: [
        { lhs: "∀x P(x)", rhs: "P(a) ∧ P(b) ∧ P(c)" },
        { lhs: "∃x P(x)", rhs: "P(a) ∨ P(b) ∨ P(c)" },
      ], note: "over the domain {a, b, c}: ∀ is a big AND, ∃ is a big OR" },
      { kind: "equiv", name: "Distributing quantifiers", rows: [
        { lhs: "∀x (P(x) ∧ Q(x))", rhs: "∀x P(x) ∧ ∀x Q(x)" },
        { lhs: "∃x (P(x) ∨ Q(x))", rhs: "∃x P(x) ∨ ∃x Q(x)" },
      ], note: "∀ distributes over ∧ and ∃ over ∨ — but NOT ∀ over ∨, nor ∃ over ∧" },
      { kind: "equiv", name: "Same-type quantifiers commute", rows: [
        { lhs: "∀x ∀y P(x, y)", rhs: "∀y ∀x P(x, y)" },
        { lhs: "∃x ∃y P(x, y)", rhs: "∃y ∃x P(x, y)" },
      ], note: "reorder freely when the quantifiers are all ∀ or all ∃" },
      { kind: "infer", name: "Mixed order — one direction only", premises: ["∃y ∀x P(x, y)"], conclusion: "∀x ∃y P(x, y)",
        note: "If a single y works for all x, then each x certainly has some y (the same one). The converse fails, so ∀x ∃y ≢ ∃y ∀x in general." },
      { kind: "text", title: "Order of nested quantifiers matters — think \"outside-in\"",
        body: "The outermost quantifier is fixed first. In ∀x ∃y L(x, y) you pick x first, then find a y that may depend on x — \"everyone has someone.\" In ∃y ∀x L(x, y) you commit to one y first and it must work for every x — \"someone is loved by everyone\" (the stronger claim)." },
    ],
  },
  {
    id: "prenex-normal-form",
    module: "m1",
    title: "Prenex Normal Form — the 4-step algorithm",
    blurb: "All quantifiers pulled to the front, leaving a quantifier-free body (the matrix). Apply the steps in order.",
    cards: [
      { kind: "text", title: "What it is",
        body: "A formula is in prenex normal form when every quantifier sits at the front and the remaining body — the matrix — is quantifier-free, e.g. ∀x ∃y (P(x) ∨ ¬Q(y)). Converting to it is good practice: it exercises implication elimination, De Morgan's for quantifiers, and variable renaming all at once." },
      { kind: "step", n: 1,
        title: "Eliminate implications",
        detail: "Rewrite → (and ↔, ⊕) with their equivalences so only ∧, ∨, ¬ remain.",
        examples: [ { from: "P → Q", to: "¬P ∨ Q" } ] },
      { kind: "step", n: 2,
        title: "Push negations inward",
        detail: "Use De Morgan's for ∧/∨ and for quantifiers, until every ¬ applies only to a predicate.",
        examples: [
          { from: "¬(P ∧ Q)", to: "¬P ∨ ¬Q" },
          { from: "¬∀x P(x)", to: "∃x ¬P(x)" },
          { from: "¬∃x P(x)", to: "∀x ¬P(x)" },
        ] },
      { kind: "step", n: 3,
        title: "Rename variables to avoid capture",
        detail: "Give bound variables fresh names so pulling a quantifier out never captures a variable used elsewhere.",
        examples: [ { from: "∀x P(x) ∧ ∃x Q(x)", to: "∀x P(x) ∧ ∃z Q(z)" } ] },
      { kind: "step", n: 4,
        title: "Pull quantifiers to the front",
        detail: "Move each quantifier outward to the head of the formula, preserving order, leaving a quantifier-free matrix.",
        examples: [ { from: "∀x P(x) ∧ ∃z Q(z)", to: "∀x ∃z (P(x) ∧ Q(z))" } ] },
    ],
  },
  {
    id: "dnf-cnf",
    module: "m1",
    title: "Converting to DNF / CNF — the 4-step algorithm",
    blurb: "Apply in order. Most conversions don't need all four steps, but in order they always reach a normal form.",
    cards: [
      {
        kind: "step", n: 1,
        title: "Eliminate every connective except ∧, ∨, ¬",
        detail: "Rewrite → and ↔ (and ⊕ if present) with their equivalences.",
        examples: [
          { from: "P → Q", to: "¬P ∨ Q" },
          { from: "P ↔ Q", to: "(P → Q) ∧ (Q → P)" },
          { from: "P ⊕ Q", to: "(P ∧ ¬Q) ∨ (¬P ∧ Q)" },
        ],
      },
      {
        kind: "step", n: 2,
        title: "Push negations inward (De Morgan)",
        detail: "Move every ¬ in until it applies only to a single variable, never a compound.",
        examples: [
          { from: "¬(P ∧ Q)", to: "¬P ∨ ¬Q" },
          { from: "¬(P ∨ Q)", to: "¬P ∧ ¬Q" },
        ],
      },
      {
        kind: "step", n: 3,
        title: "Eliminate double negations",
        examples: [
          { from: "¬(¬P)", to: "P" },
        ],
      },
      {
        kind: "step", n: 4,
        title: "Distribute to reach the desired form",
        detail: "DNF = an OR of AND-clauses; CNF = an AND of OR-clauses.",
        examples: [
          { from: "DNF: P ∧ (Q ∨ R)", to: "(P ∧ Q) ∨ (P ∧ R)" },
          { from: "CNF: P ∨ (Q ∧ R)", to: "(P ∨ Q) ∧ (P ∨ R)" },
        ],
      },
    ],
  },
];
